<?php

declare(strict_types=1);

namespace Box\Mod\Cart\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Core\Doctrine\TimestampInterface;
use FOSSBilling\Core\Doctrine\TimestampTrait;

#[ORM\Entity(repositoryClass: \Box\Mod\Cart\Repository\CartRepository::class)]
#[ORM\Table(name: 'cart')]
#[ORM\UniqueConstraint(name: 'session_id_idx', columns: ['session_id'])]
#[ORM\Index(name: 'currency_id_idx', columns: ['currency_id'])]
#[ORM\Index(name: 'cart_promo_id_idx', columns: ['promo_id'])]
#[ORM\HasLifecycleCallbacks]
class Cart implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'session_id', type: Types::STRING, length: 32, nullable: true)]
    private ?string $sessionId = null;

    #[ORM\Column(name: 'currency_id', type: Types::BIGINT, nullable: true)]
    private ?int $currencyId = null;

    #[ORM\Column(name: 'promo_id', type: Types::BIGINT, nullable: true)]
    private ?int $promoId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSessionId(): ?string
    {
        return $this->sessionId;
    }

    public function setSessionId(?string $sessionId): self
    {
        $this->sessionId = $sessionId;

        return $this;
    }

    public function getCurrencyId(): ?int
    {
        return $this->currencyId;
    }

    public function setCurrencyId(?int $currencyId): self
    {
        $this->currencyId = $currencyId;

        return $this;
    }

    public function getPromoId(): ?int
    {
        return $this->promoId;
    }

    public function setPromoId(?int $promoId): self
    {
        $this->promoId = $promoId;

        return $this;
    }
}
