<?php

declare(strict_types=1);

namespace Box\Mod\Cart\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: \Box\Mod\Cart\Repository\CartProductRepository::class)]
#[ORM\Table(name: 'cart_product')]
#[ORM\Index(name: 'cart_id_idx', columns: ['cart_id'])]
#[ORM\Index(name: 'product_id_idx', columns: ['product_id'])]
class CartProduct
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'cart_id', type: Types::BIGINT, nullable: true)]
    private ?int $cartId = null;

    #[ORM\Column(name: 'product_id', type: Types::BIGINT, nullable: true)]
    private ?int $productId = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $config = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCartId(): ?int
    {
        return $this->cartId;
    }

    public function setCartId(?int $cartId): self
    {
        $this->cartId = $cartId;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->productId;
    }

    public function setProductId(?int $productId): self
    {
        $this->productId = $productId;

        return $this;
    }

    public function getConfig(): ?string
    {
        return $this->config;
    }

    public function setConfig(?string $config): self
    {
        $this->config = $config;

        return $this;
    }
}
