    <div class="rowElem">
        <label>{% trans 'Hostname' %}:</label>
        <div class="formRight">
            <input type="text" name="config[hostname]" value="" placeholder="VPS hostname"/>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem">
        <label>{% trans 'Template' %}</label>
        <div class="formRight">
            {{ mf.selectbox('config[template]', guest.servicesolusvm_get_templates, null, 1) }}
        </div>
        <div class="fix"></div>
    </div>
