    <div class="rowElem">
        <label>{% trans 'Domain type' %}:</label>
        <div class="formRight domain-action-select">
            <input type="radio" name="config[domain_type]" value="domain" checked="checked"/><label>Domain</label>
            <input type="radio" name="config[domain_type]" value="subdomain" /><label>Subdomain</label>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem domain-action subdomain" style="display: none;">
        <label>{% trans 'Host subdomain' %}:</label>
        <div class="formRight moreFields">
            <ul>
                <li><input type="text" name="config[subdomain]" value="{{ request.subdomain }}" placeholder="{% trans 'subdomain' %}"></li>
                <li class="sep">.</li>
                <li>
                    <select name="config[master_domain]">
                        {% for subdomain in guest.serviceyouhosting_master_domains %}
                            <option value="{{ subdomain }}">{{ subdomain }}</option>
                        {% endfor %}
                    </select>
                </li>
            </ul>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem domain-action domain">
        <label>{% trans 'Host domain' %}:</label>
        <div class="formRight">
            <input type="text" name="config[domain]" value="{{ request.domain }}" placeholder="{% trans 'domain.com' %}" />
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem">
        <label>{% trans 'Information' %}:</label>
        <div class="formRight">
            Due to huge amount of spam accounts on YouHosting every new account must be approved (captcha solved) by <strong>{{ client.first_name }} {{ client.last_name }}</strong> before order can be activated.
        </div>
        <div class="fix"></div>
    </div>


    <script type="text/javascript">
        $(function() {

            $('.domain-action-select input').bind('click', function (){
                $('.domain-action').hide();
                if($(this).val() == 'domain') {
                    $('.domain-action.domain').show();
                } else {
                    $('.domain-action.subdomain').show();
                }
            });

        });
    </script>