<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Currency\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;
use Symfony\Component\Intl\Currencies;

#[ORM\Entity(repositoryClass: \Box\Mod\Currency\Repository\CurrencyRepository::class)]
#[ORM\Table(name: 'currency')]
#[ORM\HasLifecycleCallbacks]
class Currency implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => false])]
    private bool $isDefault = false;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::DECIMAL, precision: 13, scale: 6, options: ['default' => '1.000000'])]
    private string $conversionRate = '1.000000';

    private ?float $conversionRateFloat = null;

    public function __construct(
        #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 3, unique: true)]
        private string $code,
    ) {
    }

    public function toApiArray(): array
    {
        return [
            'code' => $this->getCode(),
            'name' => Currencies::getName($this->getCode()),
            'symbol' => Currencies::getSymbol($this->getCode()),
            'conversion_rate' => $this->getConversionRate(),
            'default' => $this->isDefault(),
        ];
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getCode(): string
    {
        return $this->code;
    }

    public function isDefault(): bool
    {
        return $this->isDefault;
    }

    public function getConversionRate(): float
    {
        if ($this->conversionRateFloat === null) {
            $this->conversionRateFloat = (float) $this->conversionRate;
        }

        return $this->conversionRateFloat;
    }

    public function getConversionRateRaw(): string
    {
        return $this->conversionRate;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    // --- Setters ---
    public function setIsDefault(bool $isDefault): self
    {
        $this->isDefault = $isDefault;

        return $this;
    }

    /**
     * Set the conversion rate.
     * Accepts both string and float values. The value is stored as a string
     * to preserve decimal precision in the database.
     *
     * @param string|float $conversionRate The new conversion rate
     */
    public function setConversionRate(string|float $conversionRate): self
    {
        // Use sprintf to ensure consistent decimal format (avoids scientific notation)
        // and matches the database column precision of 6 decimal places
        if (is_float($conversionRate)) {
            $this->conversionRate = sprintf('%.6f', $conversionRate);
        } else {
            $this->conversionRate = $conversionRate;
        }
        // Invalidate cached float value so it will be recalculated on next access
        $this->conversionRateFloat = null;

        return $this;
    }
}
