{% block subject %}[{{ guest.system_company.name }}] Invoice Created{% endblock %}
{% block content %}
{% apply markdown %}
Hello {{ c.first_name }} {{ c.last_name }},

This is to notify that proforma invoice {{ invoice.id }} was generated on {{ invoice.created_at|bb_date }}.
Amount Due: {{ invoice.total | money(invoice.currency) }}
Due Date: {{invoice.due_at|bb_date}}

You can view and pay the invoice at: {{'invoice'|link}}/{{invoice.hash}}

Login to members area: {{'login'|link({'email' : c.email }) }}

{{ guest.system_company.signature }}

{% endapply %}
{% endblock %}
