name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '⚠️ Potentially Breaking Changes'
    when:
      label: 'breaking change'
  - title: '🔐 Security'
    when:
      label: 'security'
  - title: '📈 Enhancements'
    when:
      label: 'enhancement'
  - title: '➕ New Features'
    when:
      label: 'feature'
  - title: '🐛 Bug Fixes'
    when:
      label: 'bug'
  - title: '📝 Changes'
    when:
      labels:
        - 'task'
        - 'tests/CI'
  - title: '📦 Dependencies'
    when:
      labels:
        - 'dependencies'
        - 'composer'
        - 'npm'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      label: 'major'
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      label: 'minor'
  - type: 'version-resolver'
    semver-increment: 'patch'
change-template: '- $TITLE (@$AUTHOR, #$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  $CHANGES
