files:
  - source: /lang/en/*.php
    translation: /lang/%two_letters_code%/%original_file_name%
"pull_request_title": "[Automated] Crowdin synchronization"
"pull_request_labels": [
  "crowdin",
  "l10n",
  "skip-changelog"
]
