version: '3.1'
services:
  web:
    image: nginx:stable
    volumes:
      - ./data/docker-nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/:/var/www/html
    ports:
      - 80:80
    networks:
      - front-tier
      - back-tier
    depends_on:
      - php

  php:
    build: './data/docker/php'
    volumes:
      - ${PWD}/:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_NAME: fossbilling
      DB_USER: root
      DB_PASS: default_mariadb_password
      PROD   : 'true'
    networks:
      - back-tier
    restart: always

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: default_mariadb_password
    networks:
    - back-tier
networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
