{% extends "layout_default.phtml" %}

{% block meta_title %}{% trans 'System under maintenance' %}{% endblock %}

{% block content %}

<div class="h-block">
    <div class="h-block-header">
        <h2>{% trans 'We are performing a regular maintenance' %}</h2>
    </div>
    <div class="block">
        <p>{% trans 'We are maintaining one or more functions. During the maintenance period, the billing system will be suspended. The services you have ordered will not be affected. We will come back later.In case of emergency, please contact us via email/phone.' %}</p>
        {% set company = guest.system_company %}
        <div class="grid_6 omega">
            <ul class="contact-us">
                <li>
                    {{ company.name }}
                </li>
                <li>
                    {{ company.address_1 }}
                </li>
                <li>
                    {{ company.address_2 }}
                </li>
                <li>
                    {{ company.address_3 }}
                </li>
                <li>
                    {{ company.tel }}
                </li>
                <li>
                    {{ company.www }}
                </li>
                <li>
                    {{ company.email }}
                </li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}