{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% block meta_title %}{% trans 'Privacy Policy' %}{% endblock %}

{% block content %}

<div class="h-block">
    <div class="h-block-header">
        <div class="icon"><span class="big-light-icon i-quote"></span></div>
        <h2>{{ company.name }} {% trans 'Privacy Policy' %}</h2>
        <p>{{ company.signature }}</p>
    </div>
    <div class="block">
        <div class="box">
            {{ company.privacy_policy|bbmd }}
        </div>
    </div>
</div>

{% endblock %}