<div class="steps">

<div class="grid_4 alpha{% if selected == 1 %} selected{% endif %}">
    <span>1</span>
    <p>{{ 'Select product'|trans }}</p>
</div>

<div class="grid_4{% if selected == 2 %} selected{% endif %}">
    <span>2</span>
    <p>{{ 'Configure'|trans }}</p>
</div>

<div class="grid_4{% if selected == 3 %} selected{% endif %}">
    <span>3</span>
    <p>{{ 'Confirm'|trans }}</p>
</div>

<div class="grid_4 omega{% if selected == 4 %} selected{% endif %}">
    <span>4</span>
    <p>{{ 'Checkout'|trans }}</p>
</div>

<div class="clear"></div>
</div>