<ul class="nav main">
    {% if not client %}
    <li>
        <a class="dark-icon i-home" href="{{ ''|link }}">{{ 'Home'|trans }}</a>
    </li>
    {% endif %}
    <li>
        <a class="dark-icon i-order" href="{{ '/order'|link }}">{{ 'Order'|trans }}</a>
    </li>

    {% if guest.extension_is_on({"mod":"news"}) %}
    <li>
        <a class="dark-icon i-blog" href="{{ '/news'|link }}">{{ 'Blog'|trans }}</a>
    </li>
    {% endif %}
    
    {% if guest.extension_is_on({"mod":"kb"}) %}
    <li>
        <a class="dark-icon i-kb" href="{{ '/kb'|link }}">{{ 'Knowledge Base'|trans }}</a>
    </li>
    {% endif %}

    {% if guest.extension_is_on({"mod":"forum"}) %}
    <li>
        <a class="dark-icon i-forum" href="{{ '/forum'|link }}">{{ 'Forum'|trans }}</a>
    </li>
    {% endif %}
    
    <li>
        <a class="dark-icon i-contacts" href="{{ '/support/contact-us'|link }}">{{ 'Contact us'|trans }}</a>
    </li>

    {% if client %}
    <li>
        <a class="dark-icon i-support" href="{{ '/support'|link }}">{{ 'Support'|trans }}</a>
    </li>
    <li>
        <a class="dark-icon i-services" href="{{ '/order/service'|link }}">{{ 'Services'|trans }}</a>
    </li>
    
    <li>
        <a class="dark-icon i-invoice" href="{{ '/invoice'|link }}">{{ 'Invoices'|trans }}</a>
    </li>
    <li>
        <a class="dark-icon i-email" href="{{ '/email'|link }}">{{ 'Emails'|trans }}</a>
    </li>

    <li>
        <a class="dark-icon i-payment" href="{{ '/client/balance'|link }}">{{ 'Payment history'|trans }}</a>
    </li>
    
    {#
    <li>
        <a class="dark-icon i-profile" href="{{ '/client/me'|link }}">{{ 'Profile'|trans }}</a>
    </li>

    <li>
        <a class="dark-icon i-logout api" href="client/client/logout">{{ 'Logout'|trans }}</a>
    </li>
    #}
    {% else %}
    {#
    <li class="secondary">
        <a class="dark-icon i-profile" href="{{ '/login'|link }}">{{ 'Sign in / Register'|trans }}</a>
    </li>
    #}
    {% endif %}
</ul>