<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Extension\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Interfaces\ApiArrayInterface;

/**
 * Installed extension record.
 *
 * The `extension` table tracks which extensions (modules, themes, payment
 * gateways, hooks, ...) are installed in this FOSSBilling instance, along
 * with their current status and version. The actual extension code lives
 * on disk; this row is only the metadata used by the extension manager.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Extension\Repository\ExtensionRepository::class)]
#[ORM\Table(name: 'extension')]
#[ORM\Index(name: 'idx_extension_type', columns: ['type'])]
class Extension implements ApiArrayInterface
{
    final public const string TYPE_MOD = 'mod';
    final public const string TYPE_THEME = 'theme';
    final public const string TYPE_PG = 'pg';
    final public const string TYPE_TRANSLATION = 'translation';
    final public const string TYPE_HOOK = 'hook';

    final public const string STATUS_INSTALLED = 'installed';
    final public const string STATUS_DEACTIVATED = 'deactivated';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $version = null;

    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type,
            'name' => $this->name,
            'status' => $this->status,
            'version' => $this->version,
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }
}
