{% set bb_editor = admin.wysiwyg_editor %}

{% if bb_editor == 'ckeditor' %}
{{ 'ckeditor/ckeditor.js' | mod_asset_url('wysiwyg') | script_tag }}
<script type="text/javascript" >
    $(document).ready(function() {
        CKEDITOR.replaceAll( '{{class}}' );    
    })

    CKEDITOR.on('instanceReady', function(){
    $.each( CKEDITOR.instances, function(instance) {
        CKEDITOR.instances[instance].on("change", function(e) {
            for ( instance in CKEDITOR.instances )
            CKEDITOR.instances[instance].updateElement();
        });
   });
});
</script>
{% endif %}