<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Servicedownloadable\Entity;

use Box\Mod\Servicedownloadable\Repository\ServiceDownloadableFileRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: ServiceDownloadableFileRepository::class)]
#[ORM\Table(name: 'service_downloadable_file')]
#[ORM\UniqueConstraint(name: 'service_downloadable_file_key_idx', columns: ['service_downloadable_id', 'file_key'])]
#[ORM\Index(name: 'service_downloadable_file_stored_filename_idx', columns: ['stored_filename'])]
#[ORM\HasLifecycleCallbacks]
class ServiceDownloadableFile implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: ServiceDownloadable::class, inversedBy: 'files')]
    #[ORM\JoinColumn(name: 'service_downloadable_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?ServiceDownloadable $service = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $label = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $downloads = 0;

    #[ORM\Column(name: 'sort_order', type: Types::INTEGER, options: ['default' => 0])]
    private int $sortOrder = 0;

    public function __construct(
        #[ORM\Column(name: 'file_key', type: Types::STRING, length: 32)]
        private string $fileKey,
        #[ORM\Column(type: Types::STRING, length: 255)]
        private string $filename,
        #[ORM\Column(name: 'stored_filename', type: Types::STRING, length: 64)]
        private string $storedFilename,
    ) {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getService(): ?ServiceDownloadable
    {
        return $this->service;
    }

    public function setService(?ServiceDownloadable $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getFileKey(): string
    {
        return $this->fileKey;
    }

    public function getFilename(): string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getStoredFilename(): string
    {
        return $this->storedFilename;
    }

    public function setStoredFilename(string $storedFilename): self
    {
        $this->storedFilename = $storedFilename;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDownloads(): int
    {
        return $this->downloads;
    }

    public function incrementDownloads(): self
    {
        ++$this->downloads;

        return $this;
    }

    public function getSortOrder(): int
    {
        return $this->sortOrder;
    }

    public function setSortOrder(int $sortOrder): self
    {
        $this->sortOrder = $sortOrder;

        return $this;
    }
}
