<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Servicedownloadable\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity]
#[ORM\Table(name: 'service_downloadable')]
#[ORM\Index(name: 'client_id_idx', columns: ['client_id'])]
#[ORM\HasLifecycleCallbacks]
class ServiceDownloadable implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::INTEGER, nullable: true)]
    private ?int $clientId = null;

    /** @var Collection<int, ServiceDownloadableFile> */
    #[ORM\OneToMany(mappedBy: 'service', targetEntity: ServiceDownloadableFile::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['sortOrder' => 'ASC', 'id' => 'ASC'])]
    private Collection $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    /** @return Collection<int, ServiceDownloadableFile> */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(ServiceDownloadableFile $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files->add($file);
            $file->setService($this);
        }

        return $this;
    }

    public function removeFile(ServiceDownloadableFile $file): self
    {
        if ($this->files->removeElement($file)) {
            $file->setService(null);
        }

        return $this;
    }

    public function findFileById(int $id): ?ServiceDownloadableFile
    {
        foreach ($this->files as $file) {
            if ($file->getId() === $id) {
                return $file;
            }
        }

        return null;
    }

    public function findFileByKey(string $fileKey): ?ServiceDownloadableFile
    {
        foreach ($this->files as $file) {
            if ($file->getFileKey() === $fileKey) {
                return $file;
            }
        }

        return null;
    }
}
