{% set currencies = guest.currency_get_pairs %}
{% if currencies|length > 1 %}
        <select name="currency" class="currency_selector input-mini pull-right">
            {% set selected = guest.cart_get_currency.code %}
            {% for code,title in currencies %}
            <option value="{{ code }}" class="currency_{{ code }}"{% if code == selected %} selected="selected"{% endif %}>{{ code }} - {{ title }}</option>
            {% endfor %}
        </select>
{% endif %}