{% block subject %}[{{ guest.system_company.name }}] Confirm Password Reset{% endblock %}
{% block content %}
{% apply markdown %}

Hello {{ c.first_name }} {{ c.last_name }},

Recently a request was submitted to reset your password for the client area.
If you did not request this, please ignore this email. It will expire and will not work in 2 hours time.

To reset your password, please visit the url below:    
{{'client/reset-password-confirm'|link}}/{{ hash }}


When you visit the link above, your password will be reset and a new 
password will be emailed to you.

To login, visit {{'login'|link({'email' : c.email }) }}
Edit your profile at {{'client/me'|link}}

{{ guest.system_company.signature }}

{% endapply %}
{% endblock %}
