{% extends "layout_public.phtml" %}
{% block meta_title %}{% trans 'About us' %}{% endblock %}
{% set company = guest.system_company %}


{% block body %}
<br/>
<section class="container" role="main">
    <div class="content-block">
        <div class="row">
            <article class="span12 data-block">
                <div class="data-container">
                    <header>
                        <h1>{% trans 'About us' %}</h1>
                        <p>{{ company.signature }}</p>
                    </header>
                    <section>
                        {{ company.note|bbmd }}
                    </section>
                </div>
            </article>
        </div>
    </div>
    <div class="offset5"><a href="{{ '/' | link}}" class="btn btn-alt btn-primary btn-large" title="Back to Homepage">{% trans 'Back to Homepage' %}</a></div>
</section>
{% endblock %}