<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Servicehosting\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Servicehosting\Repository\ServiceHostingRepository::class)]
#[ORM\Table(name: 'service_hosting')]
#[ORM\Index(name: 'service_hosting_client_id_idx', columns: ['client_id'])]
#[ORM\Index(name: 'service_hosting_server_id_idx', columns: ['service_hosting_server_id'])]
#[ORM\Index(name: 'service_hosting_hp_id_idx', columns: ['service_hosting_hp_id'])]
#[ORM\HasLifecycleCallbacks]
class ServiceHosting implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\ManyToOne(targetEntity: ServiceHostingServer::class)]
    #[ORM\JoinColumn(name: 'service_hosting_server_id', referencedColumnName: 'id', nullable: true)]
    private ?ServiceHostingServer $serviceHostingServer = null;

    #[ORM\ManyToOne(targetEntity: ServiceHostingHp::class)]
    #[ORM\JoinColumn(name: 'service_hosting_hp_id', referencedColumnName: 'id', nullable: true)]
    private ?ServiceHostingHp $serviceHostingHp = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $sld = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $tld = null;

    #[ORM\Column(type: Types::STRING, length: 45, nullable: true)]
    private ?string $ip = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $pass = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $reseller = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getServiceHostingServer(): ?ServiceHostingServer
    {
        return $this->serviceHostingServer;
    }

    public function setServiceHostingServer(?ServiceHostingServer $serviceHostingServer): self
    {
        $this->serviceHostingServer = $serviceHostingServer;

        return $this;
    }

    public function getServiceHostingHp(): ?ServiceHostingHp
    {
        return $this->serviceHostingHp;
    }

    public function setServiceHostingHp(?ServiceHostingHp $serviceHostingHp): self
    {
        $this->serviceHostingHp = $serviceHostingHp;

        return $this;
    }

    public function getSld(): ?string
    {
        return $this->sld;
    }

    public function setSld(?string $sld): self
    {
        $this->sld = $sld;

        return $this;
    }

    public function getTld(): ?string
    {
        return $this->tld;
    }

    public function setTld(?string $tld): self
    {
        $this->tld = $tld;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPass(): ?string
    {
        return $this->pass;
    }

    public function setPass(?string $pass): self
    {
        $this->pass = $pass;

        return $this;
    }

    public function isReseller(): ?bool
    {
        return $this->reseller;
    }

    public function setReseller(?bool $reseller): self
    {
        $this->reseller = $reseller;

        return $this;
    }
}
