<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Servicehosting\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampInterface;
use FOSSBilling\Doctrine\TimestampTrait;

#[ORM\Entity(repositoryClass: \Box\Mod\Servicehosting\Repository\ServiceHostingHpRepository::class)]
#[ORM\Table(name: 'service_hosting_hp')]
#[ORM\HasLifecycleCallbacks]
class ServiceHostingHp implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $quota = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $bandwidth = null;

    #[ORM\Column(name: 'max_ftp', type: Types::STRING, length: 50, nullable: true)]
    private ?string $maxFtp = null;

    #[ORM\Column(name: 'max_sql', type: Types::STRING, length: 50, nullable: true)]
    private ?string $maxSql = null;

    #[ORM\Column(name: 'max_pop', type: Types::STRING, length: 50, nullable: true)]
    private ?string $maxPop = null;

    #[ORM\Column(name: 'max_sub', type: Types::STRING, length: 50, nullable: true)]
    private ?string $maxSub = null;

    #[ORM\Column(name: 'max_park', type: Types::STRING, length: 50, nullable: true)]
    private ?string $maxPark = null;

    #[ORM\Column(name: 'max_addon', type: Types::STRING, length: 50, nullable: true)]
    private ?string $maxAddon = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $config = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getQuota(): ?string
    {
        return $this->quota;
    }

    public function setQuota(?string $quota): self
    {
        $this->quota = $quota;

        return $this;
    }

    public function getBandwidth(): ?string
    {
        return $this->bandwidth;
    }

    public function setBandwidth(?string $bandwidth): self
    {
        $this->bandwidth = $bandwidth;

        return $this;
    }

    public function getMaxFtp(): ?string
    {
        return $this->maxFtp;
    }

    public function setMaxFtp(?string $maxFtp): self
    {
        $this->maxFtp = $maxFtp;

        return $this;
    }

    public function getMaxSql(): ?string
    {
        return $this->maxSql;
    }

    public function setMaxSql(?string $maxSql): self
    {
        $this->maxSql = $maxSql;

        return $this;
    }

    public function getMaxPop(): ?string
    {
        return $this->maxPop;
    }

    public function setMaxPop(?string $maxPop): self
    {
        $this->maxPop = $maxPop;

        return $this;
    }

    public function getMaxSub(): ?string
    {
        return $this->maxSub;
    }

    public function setMaxSub(?string $maxSub): self
    {
        $this->maxSub = $maxSub;

        return $this;
    }

    public function getMaxPark(): ?string
    {
        return $this->maxPark;
    }

    public function setMaxPark(?string $maxPark): self
    {
        $this->maxPark = $maxPark;

        return $this;
    }

    public function getMaxAddon(): ?string
    {
        return $this->maxAddon;
    }

    public function setMaxAddon(?string $maxAddon): self
    {
        $this->maxAddon = $maxAddon;

        return $this;
    }

    public function getConfig(): ?string
    {
        return $this->config;
    }

    public function setConfig(?string $config): self
    {
        $this->config = $config;

        return $this;
    }
}
