<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Servicelicense\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Doctrine\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Servicelicense\Repository\ServiceLicenseRepository::class)]
#[ORM\Table(name: 'service_license')]
#[ORM\Index(name: 'service_license_client_id_idx', columns: ['client_id'])]
#[ORM\HasLifecycleCallbacks]
class ServiceLicense implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'license_key', type: Types::STRING, length: 255, unique: true, nullable: true)]
    private ?string $licenseKey = null;

    #[ORM\Column(name: 'validate_ip', type: Types::BOOLEAN)]
    private bool $validateIp = false;

    #[ORM\Column(name: 'validate_host', type: Types::BOOLEAN)]
    private bool $validateHost = false;

    #[ORM\Column(name: 'validate_path', type: Types::BOOLEAN)]
    private bool $validatePath = false;

    #[ORM\Column(name: 'validate_version', type: Types::BOOLEAN)]
    private bool $validateVersion = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $ips = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $hosts = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $paths = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $versions = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $config = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $plugin = null;

    #[ORM\Column(name: 'checked_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $checkedAt = null;

    #[ORM\Column(name: 'pinged_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $pingedAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getLicenseKey(): ?string
    {
        return $this->licenseKey;
    }

    public function setLicenseKey(?string $licenseKey): self
    {
        $this->licenseKey = $licenseKey;

        return $this;
    }

    public function isValidateIp(): bool
    {
        return $this->validateIp;
    }

    public function setValidateIp(bool $validateIp): self
    {
        $this->validateIp = $validateIp;

        return $this;
    }

    public function isValidateHost(): bool
    {
        return $this->validateHost;
    }

    public function setValidateHost(bool $validateHost): self
    {
        $this->validateHost = $validateHost;

        return $this;
    }

    public function isValidatePath(): bool
    {
        return $this->validatePath;
    }

    public function setValidatePath(bool $validatePath): self
    {
        $this->validatePath = $validatePath;

        return $this;
    }

    public function isValidateVersion(): bool
    {
        return $this->validateVersion;
    }

    public function setValidateVersion(bool $validateVersion): self
    {
        $this->validateVersion = $validateVersion;

        return $this;
    }

    public function getIps(): ?string
    {
        return $this->ips;
    }

    public function setIps(?string $ips): self
    {
        $this->ips = $ips;

        return $this;
    }

    public function getHosts(): ?string
    {
        return $this->hosts;
    }

    public function setHosts(?string $hosts): self
    {
        $this->hosts = $hosts;

        return $this;
    }

    public function getPaths(): ?string
    {
        return $this->paths;
    }

    public function setPaths(?string $paths): self
    {
        $this->paths = $paths;

        return $this;
    }

    public function getVersions(): ?string
    {
        return $this->versions;
    }

    public function setVersions(?string $versions): self
    {
        $this->versions = $versions;

        return $this;
    }

    public function getConfig(): ?string
    {
        return $this->config;
    }

    public function setConfig(?string $config): self
    {
        $this->config = $config;

        return $this;
    }

    public function getPlugin(): ?string
    {
        return $this->plugin;
    }

    public function setPlugin(?string $plugin): self
    {
        $this->plugin = $plugin;

        return $this;
    }

    public function getCheckedAt(): ?\DateTime
    {
        return $this->checkedAt;
    }

    public function setCheckedAt(?\DateTime $checkedAt): self
    {
        $this->checkedAt = $checkedAt;

        return $this;
    }

    public function getPingedAt(): ?\DateTime
    {
        return $this->pingedAt;
    }

    public function setPingedAt(?\DateTime $pingedAt): self
    {
        $this->pingedAt = $pingedAt;

        return $this;
    }

    /**
     * @return array<int, string>
     */
    public function getAllowedIps(): array
    {
        return $this->decodeList($this->ips);
    }

    /**
     * @return array<int, string>
     */
    public function getAllowedVersions(): array
    {
        return $this->decodeList($this->versions);
    }

    /**
     * @return array<int, string>
     */
    public function getAllowedHosts(): array
    {
        return $this->decodeList($this->hosts);
    }

    /**
     * @return array<int, string>
     */
    public function getAllowedPaths(): array
    {
        return $this->decodeList($this->paths);
    }

    /**
     * @return array<int, string>
     */
    private function decodeList(?string $json): array
    {
        return json_decode($json ?? '', true) ?? [];
    }
}
