{% set periods = guest.system_periods %}
{% set pricing = product.pricing %}

<section>
    <div class="well">
        <header><strong>{{ product.title }}</strong></header>
        <div class="row-fluid">
        <label class="control-label">{% trans 'Vps hostname' %} </label>
            <div class="controls">
                <input type="text" name="hostname" value="{{ request.hostname }}" placeholder="{% trans 'mydomain.com' %}">
            </div>
        </div>
        <div class="row-fluid">
        <label>{% trans 'OS template' %} </label>
            <div class="controls">
            <select name="template">
                {% for t in guest.servicesolusvm_get_templates %}
                <option value="{{t}}">{{ t|title }}</option>
                {% endfor %}
            </select>
            </div>
        </div>
    </div>

    <input type="hidden" name="single" value="1" />
    <input type="hidden" name="id" value="{{ product.id }}" />
</section>


<script type="text/javascript">
$(function() {
    $('#period-selector').change(function(){
        $('.period').hide();
        $('.period.' + $(this).val()).show();
    }).trigger('change');

    $('.addon-period-selector').change(function(){
        var r = $(this).attr('rel');
        $('#' + r + ' span').hide();
        $('#' + r + ' span.' + $(this).val()).fadeIn();
    }).trigger('change');
});
</script>
