<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Interfaces\ApiArrayInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\InvoiceItemRepository::class)]
#[ORM\Table(name: 'invoice_item')]
#[ORM\Index(name: 'invoice_id_idx', columns: ['invoice_id'])]
#[ORM\HasLifecycleCallbacks]
class InvoiceItem implements ApiArrayInterface
{
    final public const string TYPE_DEPOSIT = 'deposit';
    final public const string TYPE_CUSTOM = 'custom';
    final public const string TYPE_ORDER = 'order';
    final public const string TYPE_HOOK_CALL = 'hook_call';

    final public const string TASK_VOID = 'void';
    final public const string TASK_ACTIVATE = 'activate';
    final public const string TASK_RENEW = 'renew';

    final public const string STATUS_PENDING_PAYMENT = 'pending_payment';
    final public const string STATUS_PENDING_SETUP = 'pending_setup';
    final public const string STATUS_EXECUTED = 'executed';
    final public const string STATUS_FAILED = 'failed';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'invoice_id', type: Types::BIGINT, nullable: true)]
    private ?int $invoiceId = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(name: 'rel_id', type: Types::TEXT, nullable: true)]
    private ?string $relId = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $task = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::STRING, length: 10, nullable: true)]
    private ?string $period = null;

    #[ORM\Column(type: Types::BIGINT, nullable: true)]
    private ?int $quantity = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $unit = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $price = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true, options: ['default' => false])]
    private ?bool $charged = false;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true, options: ['default' => false])]
    private ?bool $taxed = false;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $attempts = 0;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $createdAt = null;

    #[ORM\Column(name: 'updated_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $updatedAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceId(): ?int
    {
        return $this->invoiceId;
    }

    public function setInvoiceId(?int $invoiceId): void
    {
        $this->invoiceId = $invoiceId;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    public function getRelId(): ?string
    {
        return $this->relId;
    }

    public function setRelId(?string $relId): void
    {
        $this->relId = $relId;
    }

    public function getTask(): ?string
    {
        return $this->task;
    }

    public function setTask(?string $task): void
    {
        $this->task = $task;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(?string $period): void
    {
        $this->period = $period;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): void
    {
        $this->unit = $unit;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string|int|float|null $price): void
    {
        $this->price = $price === null ? null : (string) $price;
    }

    public function getCharged(): ?bool
    {
        return $this->charged;
    }

    public function setCharged(bool|int|null $charged): void
    {
        $this->charged = $charged === null ? null : (bool) $charged;
    }

    public function getTaxed(): ?bool
    {
        return $this->taxed;
    }

    public function setTaxed(bool|int|null $taxed): void
    {
        $this->taxed = $taxed === null ? null : (bool) $taxed;
    }

    public function getAttempts(): int
    {
        return $this->attempts;
    }

    public function setAttempts(int $attempts): void
    {
        $this->attempts = $attempts;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'invoice_id' => $this->invoiceId,
            'type' => $this->type,
            'rel_id' => $this->relId,
            'task' => $this->task,
            'status' => $this->status,
            'title' => $this->title,
            'period' => $this->period,
            'quantity' => $this->quantity,
            'unit' => $this->unit,
            'price' => $this->price === null ? null : (float) $this->price,
            'charged' => (int) $this->charged,
            'taxed' => (int) $this->taxed,
            'attempts' => $this->attempts,
            'created_at' => $this->createdAt?->format('Y-m-d H:i:s'),
            'updated_at' => $this->updatedAt?->format('Y-m-d H:i:s'),
        ];
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTime();
        $this->createdAt ??= $now;
        $this->updatedAt ??= $now;
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTime();
    }
}
