<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\InvoiceRepository::class)]
#[ORM\Table(name: 'invoice')]
#[ORM\Index(name: 'client_id_idx', columns: ['client_id'])]
#[ORM\Index(name: 'invoice_status_approved_due_at_idx', columns: ['status', 'approved', 'due_at'])]
#[ORM\UniqueConstraint(name: 'hash', columns: ['hash'])]
#[ORM\HasLifecycleCallbacks]
class Invoice implements TimestampInterface
{
    use TimestampTrait;

    final public const string STATUS_PAID = 'paid';
    final public const string STATUS_UNPAID = 'unpaid';
    final public const string STATUS_REFUNDED = 'refunded';
    final public const string STATUS_CANCELED = 'canceled';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $serie = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $nr = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $hash = null;

    #[ORM\Column(type: Types::STRING, length: 25, nullable: true)]
    private ?string $currency = null;

    #[ORM\Column(name: 'currency_rate', type: Types::DECIMAL, precision: 13, scale: 6, nullable: true)]
    private ?string $currencyRate = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $credit = null;

    #[ORM\Column(name: 'base_income', type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $baseIncome = null;

    #[ORM\Column(name: 'base_refund', type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $baseRefund = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $refund = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(name: 'text_1', type: Types::TEXT, nullable: true)]
    private ?string $text1 = null;

    #[ORM\Column(name: 'text_2', type: Types::TEXT, nullable: true)]
    private ?string $text2 = null;

    #[ORM\Column(type: Types::STRING, length: 50, options: ['default' => self::STATUS_UNPAID])]
    private string $status = self::STATUS_UNPAID;

    #[ORM\Column(name: 'seller_company', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sellerCompany = null;

    #[ORM\Column(name: 'seller_company_vat', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sellerCompanyVat = null;

    #[ORM\Column(name: 'seller_company_number', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sellerCompanyNumber = null;

    #[ORM\Column(name: 'seller_address', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sellerAddress = null;

    #[ORM\Column(name: 'seller_phone', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sellerPhone = null;

    #[ORM\Column(name: 'seller_email', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sellerEmail = null;

    #[ORM\Column(name: 'buyer_first_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerFirstName = null;

    #[ORM\Column(name: 'buyer_last_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerLastName = null;

    #[ORM\Column(name: 'buyer_company', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerCompany = null;

    #[ORM\Column(name: 'buyer_company_vat', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerCompanyVat = null;

    #[ORM\Column(name: 'buyer_company_number', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerCompanyNumber = null;

    #[ORM\Column(name: 'buyer_address', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerAddress = null;

    #[ORM\Column(name: 'buyer_city', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerCity = null;

    #[ORM\Column(name: 'buyer_state', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerState = null;

    #[ORM\Column(name: 'buyer_country', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerCountry = null;

    #[ORM\Column(name: 'buyer_zip', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerZip = null;

    #[ORM\Column(name: 'buyer_phone', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerPhone = null;

    #[ORM\Column(name: 'buyer_phone_cc', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerPhoneCc = null;

    #[ORM\Column(name: 'buyer_email', type: Types::STRING, length: 255, nullable: true)]
    private ?string $buyerEmail = null;

    #[ORM\ManyToOne(targetEntity: PayGateway::class)]
    #[ORM\JoinColumn(name: 'gateway_id', referencedColumnName: 'id', nullable: true)]
    private ?PayGateway $gateway = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $approved = false;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $taxname = null;

    #[ORM\Column(type: Types::STRING, length: 35, nullable: true)]
    private ?string $taxrate = null;

    #[ORM\Column(name: 'due_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $dueAt = null;

    #[ORM\Column(name: 'reminded_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $remindedAt = null;

    #[ORM\Column(name: 'paid_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $paidAt = null;

    #[ORM\Column(name: 'hash_expires_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $hashExpiresAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(string|int|null $serie): self
    {
        $this->serie = is_int($serie) ? (string) $serie : $serie;

        return $this;
    }

    public function getNr(): ?string
    {
        return $this->nr;
    }

    public function setNr(string|int|null $nr): self
    {
        $this->nr = is_int($nr) ? (string) $nr : $nr;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(?string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getCurrencyRate(): ?string
    {
        return $this->currencyRate;
    }

    public function setCurrencyRate(string|float|null $currencyRate): self
    {
        $this->currencyRate = is_float($currencyRate) ? (string) $currencyRate : $currencyRate;

        return $this;
    }

    public function getCredit(): ?string
    {
        return $this->credit;
    }

    public function setCredit(string|int|float|null $credit): self
    {
        $this->credit = $credit === null ? null : (string) $credit;

        return $this;
    }

    public function getBaseIncome(): ?string
    {
        return $this->baseIncome;
    }

    public function setBaseIncome(string|int|float|null $baseIncome): self
    {
        $this->baseIncome = $baseIncome === null ? null : (string) $baseIncome;

        return $this;
    }

    public function getBaseRefund(): ?string
    {
        return $this->baseRefund;
    }

    public function setBaseRefund(string|int|float|null $baseRefund): self
    {
        $this->baseRefund = $baseRefund === null ? null : (string) $baseRefund;

        return $this;
    }

    public function getRefund(): ?string
    {
        return $this->refund;
    }

    public function setRefund(string|int|float|null $refund): self
    {
        $this->refund = $refund === null ? null : (string) $refund;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getText1(): ?string
    {
        return $this->text1;
    }

    public function setText1(?string $text1): self
    {
        $this->text1 = $text1;

        return $this;
    }

    public function getText2(): ?string
    {
        return $this->text2;
    }

    public function setText2(?string $text2): self
    {
        $this->text2 = $text2;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getSellerCompany(): ?string
    {
        return $this->sellerCompany;
    }

    public function setSellerCompany(?string $sellerCompany): self
    {
        $this->sellerCompany = $sellerCompany;

        return $this;
    }

    public function getSellerCompanyVat(): ?string
    {
        return $this->sellerCompanyVat;
    }

    public function setSellerCompanyVat(?string $sellerCompanyVat): self
    {
        $this->sellerCompanyVat = $sellerCompanyVat;

        return $this;
    }

    public function getSellerCompanyNumber(): ?string
    {
        return $this->sellerCompanyNumber;
    }

    public function setSellerCompanyNumber(?string $sellerCompanyNumber): self
    {
        $this->sellerCompanyNumber = $sellerCompanyNumber;

        return $this;
    }

    public function getSellerAddress(): ?string
    {
        return $this->sellerAddress;
    }

    public function setSellerAddress(?string $sellerAddress): self
    {
        $this->sellerAddress = $sellerAddress;

        return $this;
    }

    public function getSellerPhone(): ?string
    {
        return $this->sellerPhone;
    }

    public function setSellerPhone(?string $sellerPhone): self
    {
        $this->sellerPhone = $sellerPhone;

        return $this;
    }

    public function getSellerEmail(): ?string
    {
        return $this->sellerEmail;
    }

    public function setSellerEmail(?string $sellerEmail): self
    {
        $this->sellerEmail = $sellerEmail;

        return $this;
    }

    public function getBuyerFirstName(): ?string
    {
        return $this->buyerFirstName;
    }

    public function setBuyerFirstName(?string $buyerFirstName): self
    {
        $this->buyerFirstName = $buyerFirstName;

        return $this;
    }

    public function getBuyerLastName(): ?string
    {
        return $this->buyerLastName;
    }

    public function setBuyerLastName(?string $buyerLastName): self
    {
        $this->buyerLastName = $buyerLastName;

        return $this;
    }

    public function getBuyerCompany(): ?string
    {
        return $this->buyerCompany;
    }

    public function setBuyerCompany(?string $buyerCompany): self
    {
        $this->buyerCompany = $buyerCompany;

        return $this;
    }

    public function getBuyerCompanyVat(): ?string
    {
        return $this->buyerCompanyVat;
    }

    public function setBuyerCompanyVat(?string $buyerCompanyVat): self
    {
        $this->buyerCompanyVat = $buyerCompanyVat;

        return $this;
    }

    public function getBuyerCompanyNumber(): ?string
    {
        return $this->buyerCompanyNumber;
    }

    public function setBuyerCompanyNumber(?string $buyerCompanyNumber): self
    {
        $this->buyerCompanyNumber = $buyerCompanyNumber;

        return $this;
    }

    public function getBuyerAddress(): ?string
    {
        return $this->buyerAddress;
    }

    public function setBuyerAddress(?string $buyerAddress): self
    {
        $this->buyerAddress = $buyerAddress;

        return $this;
    }

    public function getBuyerCity(): ?string
    {
        return $this->buyerCity;
    }

    public function setBuyerCity(?string $buyerCity): self
    {
        $this->buyerCity = $buyerCity;

        return $this;
    }

    public function getBuyerState(): ?string
    {
        return $this->buyerState;
    }

    public function setBuyerState(?string $buyerState): self
    {
        $this->buyerState = $buyerState;

        return $this;
    }

    public function getBuyerCountry(): ?string
    {
        return $this->buyerCountry;
    }

    public function setBuyerCountry(?string $buyerCountry): self
    {
        $this->buyerCountry = $buyerCountry;

        return $this;
    }

    public function getBuyerZip(): ?string
    {
        return $this->buyerZip;
    }

    public function setBuyerZip(?string $buyerZip): self
    {
        $this->buyerZip = $buyerZip;

        return $this;
    }

    public function getBuyerPhone(): ?string
    {
        return $this->buyerPhone;
    }

    public function setBuyerPhone(?string $buyerPhone): self
    {
        $this->buyerPhone = $buyerPhone;

        return $this;
    }

    public function getBuyerPhoneCc(): ?string
    {
        return $this->buyerPhoneCc;
    }

    public function setBuyerPhoneCc(?string $buyerPhoneCc): self
    {
        $this->buyerPhoneCc = $buyerPhoneCc;

        return $this;
    }

    public function getBuyerEmail(): ?string
    {
        return $this->buyerEmail;
    }

    public function setBuyerEmail(?string $buyerEmail): self
    {
        $this->buyerEmail = $buyerEmail;

        return $this;
    }

    public function getGateway(): ?PayGateway
    {
        return $this->gateway;
    }

    public function setGateway(?PayGateway $gateway): self
    {
        $this->gateway = $gateway;

        return $this;
    }

    public function isApproved(): bool
    {
        return $this->approved;
    }

    public function setApproved(bool $approved): self
    {
        $this->approved = $approved;

        return $this;
    }

    public function getTaxname(): ?string
    {
        return $this->taxname;
    }

    public function setTaxname(?string $taxname): self
    {
        $this->taxname = $taxname;

        return $this;
    }

    public function getTaxrate(): ?string
    {
        return $this->taxrate;
    }

    public function setTaxrate(string|int|float|null $taxrate): self
    {
        $this->taxrate = is_int($taxrate) || is_float($taxrate) ? (string) $taxrate : $taxrate;

        return $this;
    }

    public function getDueAt(): ?\DateTime
    {
        return $this->dueAt;
    }

    public function setDueAt(?\DateTime $dueAt): self
    {
        $this->dueAt = $dueAt;

        return $this;
    }

    public function getRemindedAt(): ?\DateTime
    {
        return $this->remindedAt;
    }

    public function setRemindedAt(?\DateTime $remindedAt): self
    {
        $this->remindedAt = $remindedAt;

        return $this;
    }

    public function getPaidAt(): ?\DateTime
    {
        return $this->paidAt;
    }

    public function setPaidAt(?\DateTime $paidAt): self
    {
        $this->paidAt = $paidAt;

        return $this;
    }

    public function getHashExpiresAt(): ?\DateTime
    {
        return $this->hashExpiresAt;
    }

    public function setHashExpiresAt(?\DateTime $hashExpiresAt): self
    {
        $this->hashExpiresAt = $hashExpiresAt;

        return $this;
    }
}
