<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Core\Api\ArrayInterface;
use FOSSBilling\Core\Doctrine\TimestampInterface;
use FOSSBilling\Core\Doctrine\TimestampTrait;

#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\InvoiceItemRepository::class)]
#[ORM\Table(name: 'invoice_item')]
#[ORM\Index(name: 'invoice_item_invoice_id_idx', columns: ['invoice_id'])]
// rel_id is mapped TEXT (matches structure.sql exactly - the varchar(20) elsewhere in
// structure.sql that looks similar belongs to the unrelated client_balance.rel_id column), so
// this needs a MySQL-only column-length prefix on rel_id: InnoDB can't index a full TEXT column
// at all, and structure.sql's own `rel_id(20)` index has always carried the same prefix for the
// same reason - it's an index-key-length workaround, not a real 20-character data limit.
// SQLite/PostgreSQL ignore the `lengths` option entirely (AbstractPlatform::
// supportsColumnLengthIndexes() is false there), so the index they create is the full,
// unprefixed 5-column index - strictly more capable than MySQL's, not narrower. The one cost:
// that option can't round-trip through SQLite/PostgreSQL schema introspection, so
// FOSSBilling\Core\Doctrine\SchemaSynchronizer::sync() permanently reports this one index as an
// "existing structural difference" on every sync against an otherwise fully-current PG/SQLite
// database - harmless (skipped items are never applied, see SchemaSynchronizer's docblock), but
// worth knowing before treating a nonzero skip count as evidence of drift on those platforms.
#[ORM\Index(name: 'invoice_item_pending_renewal_idx', columns: ['rel_id', 'type', 'task', 'status', 'invoice_id'], options: ['lengths' => [20, null, null, null, null]])]
#[ORM\HasLifecycleCallbacks]
class InvoiceItem implements ArrayInterface, TimestampInterface
{
    use TimestampTrait;

    final public const string TYPE_DEPOSIT = 'deposit';
    final public const string TYPE_CUSTOM = 'custom';
    final public const string TYPE_ORDER = 'order';

    final public const string TASK_VOID = 'void';
    final public const string TASK_ACTIVATE = 'activate';
    final public const string TASK_RENEW = 'renew';

    final public const string STATUS_PENDING_PAYMENT = 'pending_payment';
    final public const string STATUS_PENDING_SETUP = 'pending_setup';
    final public const string STATUS_EXECUTED = 'executed';
    final public const string STATUS_FAILED = 'failed';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Invoice::class)]
    #[ORM\JoinColumn(name: 'invoice_id', referencedColumnName: 'id', nullable: true)]
    private ?Invoice $invoice = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(name: 'rel_id', type: Types::TEXT, nullable: true)]
    private ?string $relId = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $task = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::STRING, length: 10, nullable: true)]
    private ?string $period = null;

    #[ORM\Column(type: Types::BIGINT, nullable: true)]
    private ?int $quantity = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $unit = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $price = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true, options: ['default' => false])]
    private ?bool $charged = false;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true, options: ['default' => false])]
    private ?bool $taxed = false;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $attempts = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(?Invoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getRelId(): ?string
    {
        return $this->relId;
    }

    public function setRelId(?string $relId): self
    {
        $this->relId = $relId;

        return $this;
    }

    public function getTask(): ?string
    {
        return $this->task;
    }

    public function setTask(?string $task): self
    {
        $this->task = $task;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(?string $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string|int|float|null $price): self
    {
        $this->price = $price === null ? null : (string) $price;

        return $this;
    }

    public function getCharged(): ?bool
    {
        return $this->charged;
    }

    public function setCharged(bool|int|null $charged): self
    {
        $this->charged = $charged === null ? null : (bool) $charged;

        return $this;
    }

    public function getTaxed(): ?bool
    {
        return $this->taxed;
    }

    public function setTaxed(bool|int|null $taxed): self
    {
        $this->taxed = $taxed === null ? null : (bool) $taxed;

        return $this;
    }

    public function getAttempts(): int
    {
        return $this->attempts;
    }

    public function setAttempts(int $attempts): self
    {
        $this->attempts = $attempts;

        return $this;
    }

    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'invoice_id' => $this->invoice?->getId(),
            'type' => $this->type,
            'rel_id' => $this->relId,
            'task' => $this->task,
            'status' => $this->status,
            'title' => $this->title,
            'period' => $this->period,
            'quantity' => $this->quantity,
            'unit' => $this->unit,
            'price' => $this->price === null ? null : (float) $this->price,
            'charged' => (int) $this->charged,
            'taxed' => (int) $this->taxed,
            'attempts' => $this->attempts,
            'created_at' => $this->createdAt?->format('Y-m-d H:i:s'),
            'updated_at' => $this->updatedAt?->format('Y-m-d H:i:s'),
        ];
    }
}
