<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\CreatedAtTrait;

#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\InvoiceEventRepository::class)]
#[ORM\Table(name: 'invoice_event')]
#[ORM\Index(name: 'invoice_event_invoice_id_idx', columns: ['invoice_id'])]
#[ORM\HasLifecycleCallbacks]
class InvoiceEvent
{
    use CreatedAtTrait;

    final public const string TYPE_CREATED = 'created';
    final public const string TYPE_ISSUED = 'issued';
    final public const string TYPE_UPDATED = 'updated';
    final public const string TYPE_PAID = 'paid';
    final public const string TYPE_REFUNDED = 'refunded';
    final public const string TYPE_DEBITED = 'debited';
    final public const string TYPE_CANCELED = 'canceled';
    final public const string TYPE_REISSUED = 'reissued';
    final public const string TYPE_ORDER_ATTACHED = 'order_attached';
    final public const string TYPE_REMINDER = 'reminder';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'invoice_id', type: Types::BIGINT, nullable: true)]
    private ?int $invoiceId = null;

    #[ORM\Column(type: Types::STRING, length: 50)]
    private string $type = self::TYPE_UPDATED;

    #[ORM\Column(name: 'admin_id', type: Types::BIGINT, nullable: true)]
    private ?int $adminId = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $snapshot = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceId(): ?int
    {
        return $this->invoiceId;
    }

    public function setInvoiceId(?int $invoiceId): self
    {
        $this->invoiceId = $invoiceId;

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAdminId(): ?int
    {
        return $this->adminId;
    }

    public function setAdminId(?int $adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getSnapshot(): ?array
    {
        return $this->snapshot;
    }

    public function setSnapshot(?array $snapshot): self
    {
        $this->snapshot = $snapshot;

        return $this;
    }
}
