<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Core\Doctrine\TimestampInterface;
use FOSSBilling\Core\Doctrine\TimestampTrait;

/**
 * Caches the external product/price pair a gateway created for a given
 * (name, currency, amount, recurring interval) combination, for the same
 * reason - and via the same pattern - as {@see PayGatewayCustomer}: the
 * gateway's own search endpoint is only eventually consistent, so reusing
 * it as the get-or-create dedup mechanism on every checkout can mint
 * duplicate product/price objects upstream. `cacheKey` is a hash of the
 * lookup attributes rather than the raw columns, so the lookup index stays
 * small and portable across database drivers regardless of how long the
 * product name is.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\PayGatewayProductRepository::class)]
#[ORM\Table(name: 'pay_gateway_product')]
#[ORM\UniqueConstraint(name: 'pay_gateway_product_gateway_cache_key', columns: ['pay_gateway_id', 'cache_key'])]
#[ORM\HasLifecycleCallbacks]
class PayGatewayProduct implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    // See PayGatewayCustomer's equivalent column for why this cascades rather than
    // blocking gateway deletion the way Invoice/Subscription/Transaction rows do.
    #[ORM\ManyToOne(targetEntity: PayGateway::class)]
    #[ORM\JoinColumn(name: 'pay_gateway_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?PayGateway $payGateway = null;

    /**
     * sha256 of the lookup attributes (name, currency, unit amount,
     * recurring interval, recurring interval count) - see the class
     * docblock for why this is hashed rather than indexed directly.
     */
    #[ORM\Column(name: 'cache_key', type: Types::STRING, length: 64)]
    private ?string $cacheKey = null;

    #[ORM\Column(name: 'name', type: Types::STRING, length: 255)]
    private ?string $name = null;

    #[ORM\Column(name: 'external_product_id', type: Types::STRING, length: 255)]
    private ?string $externalProductId = null;

    #[ORM\Column(name: 'external_price_id', type: Types::STRING, length: 255)]
    private ?string $externalPriceId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayGateway(): ?PayGateway
    {
        return $this->payGateway;
    }

    public function setPayGateway(?PayGateway $payGateway): self
    {
        $this->payGateway = $payGateway;

        return $this;
    }

    public function getCacheKey(): ?string
    {
        return $this->cacheKey;
    }

    public function setCacheKey(?string $cacheKey): self
    {
        $this->cacheKey = $cacheKey;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getExternalProductId(): ?string
    {
        return $this->externalProductId;
    }

    public function setExternalProductId(?string $externalProductId): self
    {
        $this->externalProductId = $externalProductId;

        return $this;
    }

    public function getExternalPriceId(): ?string
    {
        return $this->externalPriceId;
    }

    public function setExternalPriceId(?string $externalPriceId): self
    {
        $this->externalPriceId = $externalPriceId;

        return $this;
    }
}
