<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * Caches the external customer record a gateway created for a client, so a
 * gateway adapter only ever needs to create one customer per (gateway,
 * client) pair instead of re-deriving it via the gateway's own (typically
 * only eventually consistent) search/list API on every checkout.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\PayGatewayCustomerRepository::class)]
#[ORM\Table(name: 'pay_gateway_customer')]
#[ORM\UniqueConstraint(name: 'pay_gateway_customer_gateway_client', columns: ['pay_gateway_id', 'client_id'])]
#[ORM\HasLifecycleCallbacks]
class PayGatewayCustomer implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    // ServicePayGateway::delete() blocks deleting a gateway with existing invoices,
    // subscriptions, or transactions - real business/audit records - but this row is
    // only a cache with no standalone meaning once its gateway is gone, so it cascades
    // instead of also blocking (or needing to be) deleted alongside the gateway.
    #[ORM\ManyToOne(targetEntity: PayGateway::class)]
    #[ORM\JoinColumn(name: 'pay_gateway_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?PayGateway $payGateway = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'external_customer_id', type: Types::STRING, length: 255)]
    private ?string $externalCustomerId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayGateway(): ?PayGateway
    {
        return $this->payGateway;
    }

    public function setPayGateway(?PayGateway $payGateway): self
    {
        $this->payGateway = $payGateway;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getExternalCustomerId(): ?string
    {
        return $this->externalCustomerId;
    }

    public function setExternalCustomerId(?string $externalCustomerId): self
    {
        $this->externalCustomerId = $externalCustomerId;

        return $this;
    }
}
