<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * Caches the external customer record a gateway created for a client, so a
 * gateway adapter only ever needs to create one customer per (gateway,
 * client) pair instead of re-deriving it via the gateway's own (typically
 * only eventually consistent) search/list API on every checkout.
 *
 * `payGatewayId` is a plain column rather than a relation to a PayGateway
 * entity: PayGateway (like the rest of the Invoice module on this branch)
 * is still RedBean-only, and FOSSBilling's schema has never had real FK
 * constraints, so there's nothing to cascade off of - ServicePayGateway::
 * delete() cleans up matching rows explicitly instead.
 *
 * `testMode` is part of the row's identity, not just informational: a
 * gateway's test and live Stripe API keys are two entirely separate
 * customer namespaces (same PayGateway row, since test_mode is just a
 * config toggle on it, not a distinct gateway). Without this, flipping a
 * gateway between test and live mode would look up - and then try to
 * charge - a customer ID that only exists in the other one.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\PayGatewayCustomerRepository::class)]
#[ORM\Table(name: 'pay_gateway_customer')]
#[ORM\UniqueConstraint(name: 'pay_gateway_customer_gateway_client_mode', columns: ['pay_gateway_id', 'client_id', 'test_mode'])]
#[ORM\HasLifecycleCallbacks]
class PayGatewayCustomer implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'pay_gateway_id', type: Types::BIGINT)]
    private ?int $payGatewayId = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'test_mode', type: Types::BOOLEAN)]
    private bool $testMode = false;

    #[ORM\Column(name: 'external_customer_id', type: Types::STRING, length: 255)]
    private ?string $externalCustomerId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayGatewayId(): ?int
    {
        return $this->payGatewayId;
    }

    public function setPayGatewayId(?int $payGatewayId): self
    {
        $this->payGatewayId = $payGatewayId;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function isTestMode(): bool
    {
        return $this->testMode;
    }

    public function setTestMode(bool $testMode): self
    {
        $this->testMode = $testMode;

        return $this;
    }

    public function getExternalCustomerId(): ?string
    {
        return $this->externalCustomerId;
    }

    public function setExternalCustomerId(?string $externalCustomerId): self
    {
        $this->externalCustomerId = $externalCustomerId;

        return $this;
    }
}
