<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Doctrine\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\SubscriptionRepository::class)]
#[ORM\Table(name: 'subscription')]
#[ORM\Index(name: 'subscription_client_id_idx', columns: ['client_id'])]
#[ORM\Index(name: 'pay_gateway_id_idx', columns: ['pay_gateway_id'])]
#[ORM\HasLifecycleCallbacks]
class Subscription implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\ManyToOne(targetEntity: PayGateway::class)]
    #[ORM\JoinColumn(name: 'pay_gateway_id', referencedColumnName: 'id', nullable: true)]
    private ?PayGateway $payGateway = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $sid = null;

    #[ORM\Column(name: 'rel_type', type: Types::STRING, length: 100, nullable: true)]
    private ?string $relType = null;

    #[ORM\Column(name: 'rel_id', type: Types::BIGINT, nullable: true)]
    private ?int $relId = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $period = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $amount = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $currency = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getPayGateway(): ?PayGateway
    {
        return $this->payGateway;
    }

    public function setPayGateway(?PayGateway $payGateway): self
    {
        $this->payGateway = $payGateway;

        return $this;
    }

    public function getSid(): ?string
    {
        return $this->sid;
    }

    public function setSid(?string $sid): self
    {
        $this->sid = $sid;

        return $this;
    }

    public function getRelType(): ?string
    {
        return $this->relType;
    }

    public function setRelType(?string $relType): self
    {
        $this->relType = $relType;

        return $this;
    }

    public function getRelId(): ?int
    {
        return $this->relId;
    }

    public function setRelId(?int $relId): self
    {
        $this->relId = $relId;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(?string $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string|int|float|null $amount): self
    {
        $this->amount = $amount === null ? null : (string) $amount;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
}
