<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Invoice\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Core\Doctrine\TimestampInterface;
use FOSSBilling\Core\Doctrine\TimestampTrait;

#[ORM\Entity(repositoryClass: \Box\Mod\Invoice\Repository\TransactionRepository::class)]
#[ORM\Table(name: '`transaction`')]
#[ORM\Index(name: 'transaction_invoice_id_idx', columns: ['invoice_id'])]
#[ORM\Index(name: 'transaction_ipn_hash_idx', columns: ['gateway_id', 'ipn_hash'])]
#[ORM\HasLifecycleCallbacks]
class Transaction implements TimestampInterface
{
    use TimestampTrait;

    final public const string STATUS_RECEIVED = 'received';
    final public const string STATUS_APPROVED = 'approved';
    final public const string STATUS_PROCESSING = 'processing';
    final public const string STATUS_PROCESSED = 'processed';
    final public const string STATUS_ERROR = 'error';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Invoice::class)]
    #[ORM\JoinColumn(name: 'invoice_id', referencedColumnName: 'id', nullable: true)]
    private ?Invoice $invoice = null;

    #[ORM\ManyToOne(targetEntity: PayGateway::class)]
    #[ORM\JoinColumn(name: 'gateway_id', referencedColumnName: 'id', nullable: true)]
    private ?PayGateway $gateway = null;

    #[ORM\Column(name: 'txn_id', type: Types::STRING, length: 255, nullable: true)]
    private ?string $txnId = null;

    #[ORM\Column(name: 'txn_status', type: Types::STRING, length: 255, nullable: true)]
    private ?string $txnStatus = null;

    #[ORM\Column(name: 's_id', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sId = null;

    #[ORM\Column(name: 's_period', type: Types::STRING, length: 255, nullable: true)]
    private ?string $sPeriod = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $amount = null;

    #[ORM\Column(type: Types::STRING, length: 10, nullable: true)]
    private ?string $currency = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(type: Types::STRING, length: 255, options: ['default' => self::STATUS_RECEIVED])]
    private string $status = self::STATUS_RECEIVED;

    #[ORM\Column(type: Types::STRING, length: 45, nullable: true)]
    private ?string $ip = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $error = null;

    #[ORM\Column(name: 'error_code', type: Types::INTEGER, nullable: true)]
    private ?int $errorCode = null;

    #[ORM\Column(name: 'validate_ipn', type: Types::BOOLEAN, options: ['default' => true])]
    private bool $validateIpn = true;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $ipn = null;

    #[ORM\Column(name: 'ipn_hash', type: Types::STRING, length: 64, nullable: true)]
    private ?string $ipnHash = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $output = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $note = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(?Invoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function getGateway(): ?PayGateway
    {
        return $this->gateway;
    }

    public function setGateway(?PayGateway $gateway): self
    {
        $this->gateway = $gateway;

        return $this;
    }

    public function getTxnId(): ?string
    {
        return $this->txnId;
    }

    public function setTxnId(?string $txnId): self
    {
        $this->txnId = $txnId;

        return $this;
    }

    public function getTxnStatus(): ?string
    {
        return $this->txnStatus;
    }

    public function setTxnStatus(?string $txnStatus): self
    {
        $this->txnStatus = $txnStatus;

        return $this;
    }

    public function getSId(): ?string
    {
        return $this->sId;
    }

    public function setSId(?string $sId): self
    {
        $this->sId = $sId;

        return $this;
    }

    public function getSPeriod(): ?string
    {
        return $this->sPeriod;
    }

    public function setSPeriod(?string $sPeriod): self
    {
        $this->sPeriod = $sPeriod;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string|int|float|null $amount): self
    {
        $this->amount = $amount === null ? null : (string) $amount;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getError(): ?string
    {
        return $this->error;
    }

    public function setError(?string $error): self
    {
        $this->error = $error;

        return $this;
    }

    public function getErrorCode(): ?int
    {
        return $this->errorCode;
    }

    public function setErrorCode(?int $errorCode): self
    {
        $this->errorCode = $errorCode;

        return $this;
    }

    public function isValidateIpn(): bool
    {
        return $this->validateIpn;
    }

    public function setValidateIpn(bool $validateIpn): self
    {
        $this->validateIpn = $validateIpn;

        return $this;
    }

    public function getIpn(): ?string
    {
        return $this->ipn;
    }

    public function setIpn(?string $ipn): self
    {
        $this->ipn = $ipn;

        return $this;
    }

    public function getIpnHash(): ?string
    {
        return $this->ipnHash;
    }

    public function setIpnHash(?string $ipnHash): self
    {
        $this->ipnHash = $ipnHash;

        return $this;
    }

    public function getOutput(): ?string
    {
        return $this->output;
    }

    public function setOutput(?string $output): self
    {
        $this->output = $output;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }
}
