<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Email\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;
use FOSSBilling\Tools;

/**
 * One row per email that FOSSBilling sent to a client.
 *
 * Used as a delivery log and to power the "resend" action on the
 * client-facing email history view.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Email\Repository\ActivityClientEmailRepository::class)]
#[ORM\Table(name: 'activity_client_email')]
#[ORM\HasLifecycleCallbacks]
class ActivityClientEmail implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::INTEGER, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $sender = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $recipients = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(name: 'content_html', type: Types::TEXT, nullable: true)]
    private ?string $contentHtml = null;

    #[ORM\Column(name: 'content_text', type: Types::TEXT, nullable: true)]
    private ?string $contentText = null;

    #[ORM\Column(name: 'attachment_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $attachmentName = null;

    #[ORM\Column(name: 'attachment_content', type: Types::BLOB, nullable: true)]
    private mixed $attachmentContent = null;

    #[ORM\Column(name: 'attachment_mime', type: Types::STRING, length: 100, nullable: true)]
    private ?string $attachmentMime = null;

    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'client_id' => $this->clientId,
            'sender' => $this->sender,
            'recipients' => $this->recipients,
            'subject' => $this->subject,
            'content_html' => Tools::sanitizeContent($this->contentHtml ?? ''),
            'content_text' => $this->contentText,
            'has_attachment' => $this->attachmentName !== null,
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getSender(): ?string
    {
        return $this->sender;
    }

    public function setSender(?string $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipients(): ?string
    {
        return $this->recipients;
    }

    public function setRecipients(?string $recipients): self
    {
        $this->recipients = $recipients;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getContentHtml(): ?string
    {
        return $this->contentHtml;
    }

    public function setContentHtml(?string $contentHtml): self
    {
        $this->contentHtml = $contentHtml;

        return $this;
    }

    public function getContentText(): ?string
    {
        return $this->contentText;
    }

    public function setContentText(?string $contentText): self
    {
        $this->contentText = $contentText;

        return $this;
    }

    public function getAttachmentName(): ?string
    {
        return $this->attachmentName;
    }

    public function setAttachmentName(?string $attachmentName): self
    {
        $this->attachmentName = $attachmentName;

        return $this;
    }

    public function getAttachmentContent(): ?string
    {
        if (is_resource($this->attachmentContent)) {
            return stream_get_contents($this->attachmentContent) ?: null;
        }

        return $this->attachmentContent;
    }

    public function setAttachmentContent(?string $attachmentContent): self
    {
        $this->attachmentContent = $attachmentContent;

        return $this;
    }

    public function getAttachmentMime(): ?string
    {
        return $this->attachmentMime;
    }

    public function setAttachmentMime(?string $attachmentMime): self
    {
        $this->attachmentMime = $attachmentMime;

        return $this;
    }
}
