<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Email\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\CreatedAtTrait;
use FOSSBilling\Api\ArrayInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Email\Repository\EmailTemplateGroupRepository::class)]
#[ORM\Table(name: 'email_template_group')]
// Doctrine\ORM\Mapping\Table's $uniqueConstraints constructor param is a documented no-op
// (see the Deprecation::trigger() in its constructor) - it must be a standalone attribute.
#[ORM\UniqueConstraint(name: 'email_template_group_unique', columns: ['email_template_id', 'admin_group_id'])]
#[ORM\Index(name: 'email_template_group_group_id_idx', columns: ['admin_group_id'])]
#[ORM\HasLifecycleCallbacks]
class EmailTemplateGroup implements ArrayInterface
{
    use CreatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    public function __construct(
        #[ORM\ManyToOne(targetEntity: EmailTemplate::class)]
        #[ORM\JoinColumn(name: 'email_template_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
        private EmailTemplate $emailTemplate,
        #[ORM\Column(name: 'admin_group_id', type: Types::BIGINT)]
        private int $adminGroupId,
    ) {
    }

    public function toApiArray(): array
    {
        return [
            'id' => $this->getId(),
            'email_template_id' => $this->getEmailTemplate()->getId(),
            'admin_group_id' => $this->getAdminGroupId(),
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmailTemplate(): EmailTemplate
    {
        return $this->emailTemplate;
    }

    public function setEmailTemplate(EmailTemplate $emailTemplate): self
    {
        $this->emailTemplate = $emailTemplate;

        return $this;
    }

    public function getAdminGroupId(): int
    {
        return $this->adminGroupId;
    }

    public function setAdminGroupId(int $adminGroupId): self
    {
        $this->adminGroupId = $adminGroupId;

        return $this;
    }
}
