<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Email\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * Pending email in the queue processed by the email-batch cron task.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Email\Repository\QueuedEmailRepository::class)]
#[ORM\Table(name: 'email_queue')]
#[ORM\HasLifecycleCallbacks]
class QueuedEmail implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    public const STATUS_PENDING = 'pending';
    public const STATUS_SENT = 'sent';
    public const STATUS_FAILED = 'failed';
    public const STATUS_UNSENT = 'unsent';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $recipient;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $sender;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $subject;

    #[ORM\Column(type: Types::TEXT)]
    private string $content;

    #[ORM\Column(name: 'to_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $toName = null;

    #[ORM\Column(name: 'from_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $fromName = null;

    #[ORM\Column(name: 'client_id', type: Types::INTEGER, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'admin_id', type: Types::INTEGER, nullable: true)]
    private ?int $adminId = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $priority = null;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $tries = 0;

    #[ORM\Column(type: Types::STRING, length: 20, options: ['default' => self::STATUS_PENDING])]
    private string $status = self::STATUS_PENDING;

    #[ORM\Column(name: 'attachment_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $attachmentName = null;

    #[ORM\Column(name: 'attachment_content', type: Types::BLOB, nullable: true)]
    private mixed $attachmentContent = null;

    #[ORM\Column(name: 'attachment_mime', type: Types::STRING, length: 100, nullable: true)]
    private ?string $attachmentMime = null;

    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'recipient' => $this->recipient,
            'subject' => $this->subject,
            'content' => $this->content,
            'to_name' => $this->toName,
            'status' => $this->status,
            'tries' => $this->tries,
            'has_attachment' => $this->attachmentName !== null,
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecipient(): string
    {
        return $this->recipient;
    }

    public function setRecipient(string $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getSender(): string
    {
        return $this->sender;
    }

    public function setSender(string $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getSubject(): string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getToName(): ?string
    {
        return $this->toName;
    }

    public function setToName(?string $toName): self
    {
        $this->toName = $toName;

        return $this;
    }

    public function getFromName(): ?string
    {
        return $this->fromName;
    }

    public function setFromName(?string $fromName): self
    {
        $this->fromName = $fromName;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getAdminId(): ?int
    {
        return $this->adminId;
    }

    public function setAdminId(?int $adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getTries(): int
    {
        return $this->tries;
    }

    public function setTries(int $tries): self
    {
        $this->tries = $tries;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAttachmentName(): ?string
    {
        return $this->attachmentName;
    }

    public function setAttachmentName(?string $attachmentName): self
    {
        $this->attachmentName = $attachmentName;

        return $this;
    }

    public function getAttachmentContent(): ?string
    {
        if (is_resource($this->attachmentContent)) {
            return stream_get_contents($this->attachmentContent) ?: null;
        }

        return $this->attachmentContent;
    }

    public function setAttachmentContent(?string $attachmentContent): self
    {
        $this->attachmentContent = $attachmentContent;

        return $this;
    }

    public function getAttachmentMime(): ?string
    {
        return $this->attachmentMime;
    }

    public function setAttachmentMime(?string $attachmentMime): self
    {
        $this->attachmentMime = $attachmentMime;

        return $this;
    }
}
