<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Staff\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Interfaces\ApiArrayInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Staff\Repository\AdminGroupMemberRepository::class)]
#[ORM\Table(name: 'admin_group_member', uniqueConstraints: [new ORM\UniqueConstraint(name: 'admin_group_member_unique', columns: ['admin_id', 'admin_group_id'])])]
#[ORM\HasLifecycleCallbacks]
class AdminGroupMember implements ApiArrayInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $createdAt = null;

    public function __construct(
        #[ORM\Column(name: 'admin_id', type: Types::INTEGER)]
        private int $adminId,
        #[ORM\ManyToOne(targetEntity: AdminGroup::class)]
        #[ORM\JoinColumn(name: 'admin_group_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
        private AdminGroup $adminGroup,
    ) {
    }

    public function toApiArray(): array
    {
        return [
            'id' => $this->getId(),
            'admin_id' => $this->getAdminId(),
            'admin_group_id' => $this->getAdminGroup()->getId(),
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $this->createdAt ??= new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdminId(): int
    {
        return $this->adminId;
    }

    public function setAdminId(int $adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }

    public function getAdminGroup(): AdminGroup
    {
        return $this->adminGroup;
    }

    public function setAdminGroup(AdminGroup $adminGroup): self
    {
        $this->adminGroup = $adminGroup;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}
