<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * Copyright 2011-2021 BoxBilling, Inc.
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Staff\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Interfaces\ApiArrayInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Staff\Repository\AdminGroupRepository::class)]
#[ORM\Table(name: 'admin_group')]
#[ORM\HasLifecycleCallbacks]
class AdminGroup implements ApiArrayInterface
{
    public const string SYSTEM_SUPER_ADMIN = 'super_admin';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(name: 'system_name', type: Types::STRING, length: 100, nullable: true, unique: true)]
    private ?string $systemName = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $permissions = null;

    #[ORM\Column(name: 'protected', type: Types::BOOLEAN, options: ['default' => false])]
    private bool $protected = false;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $createdAt = null;

    #[ORM\Column(name: 'updated_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $updatedAt = null;

    public function toApiArray(): array
    {
        return [
            'id' => $this->getId(),
            'name' => $this->getName(),
            'system_name' => $this->getSystemName(),
            'permissions' => $this->getPermissions(),
            'protected' => $this->isProtected(),
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTime();
        $this->createdAt ??= $now;
        $this->updatedAt ??= $now;
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSystemName(): ?string
    {
        return $this->systemName;
    }

    public function setSystemName(?string $systemName): self
    {
        $this->systemName = $systemName;

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function getPermissions(): array
    {
        if ($this->permissions === null || $this->permissions === '') {
            return [];
        }

        $permissions = json_decode($this->permissions, true);

        return is_array($permissions) ? $permissions : [];
    }

    /**
     * @param array<string, mixed>|null $permissions
     */
    public function setPermissions(?array $permissions): self
    {
        $this->permissions = empty($permissions) ? null : json_encode($permissions, JSON_THROW_ON_ERROR);

        return $this;
    }

    public function getPermissionsJson(): ?string
    {
        return $this->permissions;
    }

    public function setPermissionsJson(?string $permissions): self
    {
        $this->permissions = $permissions;

        return $this;
    }

    public function isProtected(): bool
    {
        return $this->protected;
    }

    public function setProtected(bool $protected): self
    {
        $this->protected = $protected;

        return $this;
    }

    public function isSuperAdministrator(): bool
    {
        return $this->systemName === self::SYSTEM_SUPER_ADMIN;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}
