<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{% block meta_title %}{% endblock %}</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    
    {% include "partial_bb_meta.phtml" %}
    
    <link rel="stylesheet" href="css/main.css" type="text/css" media="screen" />
    <link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet" type="text/css" />
    
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.alerts.js"></script>
    <script type="text/javascript" src="js/ui/jquery.tipsy.js"></script>
    <script type="text/javascript" src="js/jquery.collapsible.min.js"></script>
    <script type="text/javascript" src="js/forms/forms.js"></script>
    <script type="text/javascript" src="js/jquery.ToTop.js"></script>
    <script type="text/javascript" src="js/jquery.scrollTo-min.js"></script>
    <script type="text/javascript" src="js/jquery-ui.js"></script>
    <script type="text/javascript" src="js/bb-admin.js?v={{guest.system_version}}"></script>
</head>

<body>
<!-- Top navigation bar -->
<div id="topNav">
    <div class="fixed">
        <div class="wrapper">
            <div class="backTo"><a href="{{ '/'|link }}" title=""><img src="images/icons/topnav/mainWebsite.png" alt="" /><span>{% trans 'Main website' %}</span></a></div>
            <div class="userNav">
                <ul>
                    <li class="loading" style="display:none;"><img src="images/loader.gif" alt="" /><span>{% trans 'Loading ...' %}</span></li>
                    <li><a href="http://www.boxbilling.com/docs{% if help_query %}/search.html?q={{help_query}}{% endif %}" title="" target="_blank"><img src="images/icons/topnav/help.png" alt="" /><span>{% trans 'Help' %}</span></a></li>
                </ul>
            </div>
            <div class="fix"></div>
        </div>
    </div>
</div>

{% block content %}{% endblock %}

<!-- Footer -->
<div id="footer">
	<div class="wrapper">
    	{% include "partial_footer.phtml" with {'product': product} %}
    </div>
</div>
{% block js %}{% endblock %}
</body>
</html>
