{% extends "layout_default.phtml" %}

{% block meta_title %}{% trans 'Staff Group management' %}{% endblock %}
{% set active_menu = 'system' %}


{% block breadcrumbs %}
<ul>
    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li><a href="{{ 'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li><a href="{{ 'extension/settings/staff'|alink }}">{% trans 'Staff' %}</a></li>
    <li><a href="{{ 'extension/settings/staff'|alink }}#tab-groups">{% trans 'Groups' %}</a></li>
    <li class="lastB">{{group.name}}</li>
</ul>
{% endblock %}

{% block content %}

<div class="widget">

    <div class="head">
        <h5>{% trans 'Manage staff member details' %}</h5>
    </div>

    <form method="post" action="{{ 'api/admin/staff/group_update'|link }}" class="mainForm api-form" data-api-msg="{% trans 'Staff group updated' %}">
        <fieldset>
            <div class="rowElem noborder">
                <label for="name">{% trans 'Name' %}</label>
                <div class="formRight">
                    <input type="text" name="name" value="{{group.name}}" required="required"/>
                </div>
                <div class="fix"></div>
            </div>
            <input type="hidden" name="id" value="{{ group.id }}">
            <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" />
        </fieldset>
    </form>
</div>

{% endblock %}