    <link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="css/main.css?v={{guest.system_version}}" type="text/css" media="screen" />
    <link rel="stylesheet" href="css/bb.css?v={{guest.system_version}}" type="text/css" media="screen" />
    <link rel="stylesheet" href="css/dark-icons-sprite.css?v={{guest.system_version}}" type="text/css" media="screen" />
    <link href="css/jquery-ui.css?v={{guest.system_version}}" rel="stylesheet" type="text/css" />