<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Client\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * Links a client to a client group. A client may hold membership in more
 * than one group; the pair is unique. Rows have no standalone meaning once
 * either side is gone, so both relations cascade on delete.
 */
#[ORM\Entity(repositoryClass: \Box\Mod\Client\Repository\ClientGroupMembershipRepository::class)]
#[ORM\Table(name: 'client_group_members')]
#[ORM\UniqueConstraint(name: 'client_group_members_client_group', columns: ['client_id', 'client_group_id'])]
#[ORM\Index(name: 'client_group_members_group_idx', columns: ['client_group_id'])]
#[ORM\HasLifecycleCallbacks]
class ClientGroupMembership implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'groupMemberships')]
    #[ORM\JoinColumn(name: 'client_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?Client $client = null;

    #[ORM\ManyToOne(targetEntity: ClientGroup::class)]
    #[ORM\JoinColumn(name: 'client_group_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?ClientGroup $clientGroup = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getClientGroup(): ?ClientGroup
    {
        return $this->clientGroup;
    }

    public function setClientGroup(?ClientGroup $clientGroup): self
    {
        $this->clientGroup = $clientGroup;

        return $this;
    }
}
