<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Client\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Client\Repository\ClientBalanceRepository::class)]
#[ORM\Table(name: 'client_balance')]
#[ORM\Index(name: 'client_balance_client_id_idx', columns: ['client_id'])]
#[ORM\UniqueConstraint(name: 'uniq_invoice_item_credit', columns: ['invoice_item_id'])]
#[ORM\HasLifecycleCallbacks]
class ClientBalance implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Client::class)]
    #[ORM\JoinColumn(name: 'client_id', referencedColumnName: 'id', nullable: true)]
    private ?Client $client = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(name: 'rel_id', type: Types::STRING, length: 20, nullable: true)]
    private ?string $relId = null;

    #[ORM\Column(name: 'invoice_item_id', type: Types::BIGINT, nullable: true)]
    private ?int $invoiceItemId = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true, options: ['default' => '0.00'])]
    private ?string $amount = '0.00';

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getRelId(): ?string
    {
        return $this->relId;
    }

    public function setRelId(?string $relId): self
    {
        $this->relId = $relId;

        return $this;
    }

    public function getInvoiceItemId(): ?int
    {
        return $this->invoiceItemId;
    }

    public function setInvoiceItemId(?int $invoiceItemId): self
    {
        $this->invoiceItemId = $invoiceItemId;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(?string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}
