{% block subject %}[{{ guest.system_company.name }}] {{ticket.subject}}{% endblock %}
{% block content %}
{% filter markdown %}

Hi {{ ticket.author_name }},

New reply was posted to request **{{ticket.subject}}**

You can track and respond to this conversation at:

{{'support/contact-us/conversation'|link }}/{{ ticket.hash }}
      
Please do not reply to this email directly. Use the link provided above.
      
{{ guest.system_company.signature }}

{% endfilter %}
{% endblock %}
