<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Formbuilder\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Formbuilder\Repository\FormFieldRepository::class)]
#[ORM\Table(name: 'form_field')]
#[ORM\Index(name: 'form_id_idx', columns: ['form_id'])]
#[ORM\HasLifecycleCallbacks]
class FormField implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'form_id', type: Types::INTEGER, nullable: true)]
    private ?int $formId = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $label = null;

    #[ORM\Column(name: 'hide_label', type: Types::BOOLEAN, nullable: true)]
    private ?bool $hideLabel = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(name: 'default_value', type: Types::STRING, length: 255, nullable: true)]
    private ?string $defaultValue = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $required = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $hidden = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $readonly = null;

    #[ORM\Column(name: 'is_unique', type: Types::BOOLEAN, nullable: true)]
    private ?bool $isUnique = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $prefix = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $suffix = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $options = null;

    #[ORM\Column(name: 'show_initial', type: Types::STRING, length: 255, nullable: true)]
    private ?string $showInitial = null;

    #[ORM\Column(name: 'show_middle', type: Types::STRING, length: 255, nullable: true)]
    private ?string $showMiddle = null;

    #[ORM\Column(name: 'show_prefix', type: Types::STRING, length: 255, nullable: true)]
    private ?string $showPrefix = null;

    #[ORM\Column(name: 'show_suffix', type: Types::STRING, length: 255, nullable: true)]
    private ?string $showSuffix = null;

    #[ORM\Column(name: 'text_size', type: Types::INTEGER, nullable: true)]
    private ?int $textSize = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFormId(): ?int
    {
        return $this->formId;
    }

    public function setFormId(?int $formId): self
    {
        $this->formId = $formId;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function isHideLabel(): bool
    {
        return $this->hideLabel ?? false;
    }

    public function setHideLabel(bool $hideLabel): self
    {
        $this->hideLabel = $hideLabel;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDefaultValue(): ?string
    {
        return $this->defaultValue;
    }

    public function setDefaultValue(?string $defaultValue): self
    {
        $this->defaultValue = $defaultValue;

        return $this;
    }

    public function isRequired(): bool
    {
        return $this->required ?? false;
    }

    public function setRequired(bool $required): self
    {
        $this->required = $required;

        return $this;
    }

    public function isHidden(): bool
    {
        return $this->hidden ?? false;
    }

    public function setHidden(bool $hidden): self
    {
        $this->hidden = $hidden;

        return $this;
    }

    public function isReadonly(): bool
    {
        return $this->readonly ?? false;
    }

    public function setReadonly(bool $readonly): self
    {
        $this->readonly = $readonly;

        return $this;
    }

    public function isUnique(): bool
    {
        return $this->isUnique ?? false;
    }

    public function setIsUnique(bool $isUnique): self
    {
        $this->isUnique = $isUnique;

        return $this;
    }

    public function getPrefix(): ?string
    {
        return $this->prefix;
    }

    public function setPrefix(?string $prefix): self
    {
        $this->prefix = $prefix;

        return $this;
    }

    public function getSuffix(): ?string
    {
        return $this->suffix;
    }

    public function setSuffix(?string $suffix): self
    {
        $this->suffix = $suffix;

        return $this;
    }

    public function getOptions(): ?string
    {
        return $this->options;
    }

    public function setOptions(?string $options): self
    {
        $this->options = $options;

        return $this;
    }

    public function getShowInitial(): ?string
    {
        return $this->showInitial;
    }

    public function setShowInitial(?string $showInitial): self
    {
        $this->showInitial = $showInitial;

        return $this;
    }

    public function getShowMiddle(): ?string
    {
        return $this->showMiddle;
    }

    public function setShowMiddle(?string $showMiddle): self
    {
        $this->showMiddle = $showMiddle;

        return $this;
    }

    public function getShowPrefix(): ?string
    {
        return $this->showPrefix;
    }

    public function setShowPrefix(?string $showPrefix): self
    {
        $this->showPrefix = $showPrefix;

        return $this;
    }

    public function getShowSuffix(): ?string
    {
        return $this->showSuffix;
    }

    public function setShowSuffix(?string $showSuffix): self
    {
        $this->showSuffix = $showSuffix;

        return $this;
    }

    public function getTextSize(): ?int
    {
        return $this->textSize;
    }

    public function setTextSize(?int $textSize): self
    {
        $this->textSize = $textSize;

        return $this;
    }
}
