{% if order.status == 'active' %}
<div class="widget">
    <div class="head">
        <h2 class="dark-icon i-downloads">{{ service.title }}</h2>
    </div>
    <div class="grid_12 alpha omega">
        <div class="box">
            <h2>{% trans 'Download file' %}</h2>
            <div class="block">
                <a class="bb-button bb-button-submit" href="{{ 'servicedownloadable/get-file'|link }}/{{ order.id }}"><span class="light-icon i-downloads"></span> {% trans 'Download' %}</a>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
{% endif %}