<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Product\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Period;

#[ORM\Entity]
#[ORM\Table(name: 'product_payment_period')]
#[ORM\UniqueConstraint(name: 'product_payment_period_unique', columns: ['product_payment_id', 'code'])]
class ProductPaymentPeriod
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: ProductPayment::class, inversedBy: 'periods')]
    #[ORM\JoinColumn(name: 'product_payment_id', nullable: false)]
    private ProductPayment $productPayment;

    #[ORM\Column(name: 'code', type: \Doctrine\DBAL\Types\Types::STRING, length: 10)]
    private string $code;

    #[ORM\Column(name: 'price', type: \Doctrine\DBAL\Types\Types::DECIMAL, precision: 18, scale: 2, options: ['default' => '0.00'])]
    private string $price = '0.00';

    #[ORM\Column(name: 'setup_price', type: \Doctrine\DBAL\Types\Types::DECIMAL, precision: 18, scale: 2, options: ['default' => '0.00'])]
    private string $setupPrice = '0.00';

    #[ORM\Column(name: 'enabled', type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => true])]
    private bool $enabled = true;

    #[ORM\Column(name: 'sort_order', type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['default' => 0])]
    private int $sortOrder = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductPayment(): ProductPayment
    {
        return $this->productPayment;
    }

    public function setProductPayment(ProductPayment $productPayment): self
    {
        $this->productPayment = $productPayment;

        return $this;
    }

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getPrice(): float
    {
        return (float) $this->price;
    }

    public function setPrice(float|int|string $price): self
    {
        $this->price = sprintf('%.2f', (float) $price);

        return $this;
    }

    public function getSetupPrice(): float
    {
        return (float) $this->setupPrice;
    }

    public function setSetupPrice(float|int|string $setupPrice): self
    {
        $this->setupPrice = sprintf('%.2f', (float) $setupPrice);

        return $this;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getSortOrder(): int
    {
        return $this->sortOrder;
    }

    public function setSortOrder(int $sortOrder): self
    {
        $this->sortOrder = $sortOrder;

        return $this;
    }

    /**
     * Parses this period's code (e.g. "1M", "3Y", "45D") into a billing period value object.
     */
    public function getPeriod(): Period
    {
        return new Period($this->code);
    }
}
