<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Product\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: \Box\Mod\Product\Repository\ProductPaymentRepository::class)]
#[ORM\Table(name: 'product_payment')]
class ProductPayment
{
    final public const string FREE = 'free';
    final public const string ONCE = 'once';
    final public const string RECURRENT = 'recurrent';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 30, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(name: 'once_price', type: \Doctrine\DBAL\Types\Types::DECIMAL, precision: 18, scale: 2, options: ['default' => '0.00'])]
    private string $oncePrice = '0.00';

    #[ORM\Column(name: 'once_setup_price', type: \Doctrine\DBAL\Types\Types::DECIMAL, precision: 18, scale: 2, options: ['default' => '0.00'])]
    private string $onceSetupPrice = '0.00';

    /**
     * @var Collection<int, ProductPaymentPeriod>
     */
    #[ORM\OneToMany(mappedBy: 'productPayment', targetEntity: ProductPaymentPeriod::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $periods;

    public function __construct()
    {
        $this->periods = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getOncePrice(): float
    {
        return (float) $this->oncePrice;
    }

    public function setOncePrice(float|int|string $price): self
    {
        $this->oncePrice = sprintf('%.2f', (float) $price);

        return $this;
    }

    public function getOnceSetupPrice(): float
    {
        return (float) $this->onceSetupPrice;
    }

    public function setOnceSetupPrice(float|int|string $price): self
    {
        $this->onceSetupPrice = sprintf('%.2f', (float) $price);

        return $this;
    }

    /**
     * @return Collection<int, ProductPaymentPeriod>
     */
    public function getPeriods(): Collection
    {
        return $this->periods;
    }

    /**
     * Finds a configured billing period by its Box_Period code (e.g. "1M", "3Y", "45D").
     */
    public function getPeriod(string $code): ?ProductPaymentPeriod
    {
        foreach ($this->periods as $period) {
            if ($period->getCode() === $code) {
                return $period;
            }
        }

        return null;
    }

    public function addPeriod(ProductPaymentPeriod $period): self
    {
        if (!$this->periods->contains($period)) {
            $this->periods->add($period);
            $period->setProductPayment($this);
        }

        return $this;
    }

    public function removePeriod(ProductPaymentPeriod $period): self
    {
        $this->periods->removeElement($period);

        return $this;
    }
}
