<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Product\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Product\Repository\ProductRepository::class)]
#[ORM\Table(name: 'product')]
#[ORM\HasLifecycleCallbacks]
class Product implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'product_category_id', type: \Doctrine\DBAL\Types\Types::INTEGER, nullable: true)]
    private ?int $productCategoryId = null;

    #[ORM\Column(name: 'product_payment_id', type: \Doctrine\DBAL\Types\Types::INTEGER, nullable: true)]
    private ?int $productPaymentId = null;

    #[ORM\Column(name: 'form_id', type: \Doctrine\DBAL\Types\Types::INTEGER, nullable: true)]
    private ?int $formId = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 50, options: ['default' => 'product'])]
    private string $unit = 'product';

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => true])]
    private bool $active = true;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 50, options: ['default' => 'enabled'])]
    private string $status = 'enabled';

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => false])]
    private bool $hidden = false;

    #[ORM\Column(name: 'is_addon', type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => false])]
    private bool $isAddon = false;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 50, options: ['default' => 'after_payment'])]
    private string $setup = 'after_payment';

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $addons = null;

    #[ORM\Column(name: 'icon_url', type: \Doctrine\DBAL\Types\Types::STRING, length: 255, nullable: true)]
    private ?string $iconUrl = null;

    #[ORM\Column(name: 'allow_quantity_select', type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => false])]
    private bool $allowQuantitySelect = false;

    #[ORM\Column(name: 'stock_control', type: \Doctrine\DBAL\Types\Types::BOOLEAN, options: ['default' => false])]
    private bool $stockControl = false;

    #[ORM\Column(name: 'quantity_in_stock', type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['default' => 0])]
    private int $quantityInStock = 0;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 255, nullable: true)]
    private ?string $plugin = null;

    #[ORM\Column(name: 'plugin_config', type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $pluginConfig = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $upgrades = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER, nullable: true)]
    private ?int $priority = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $config = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 255, nullable: true)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductCategoryId(): ?int
    {
        return $this->productCategoryId;
    }

    public function setProductCategoryId(?int $productCategoryId): self
    {
        $this->productCategoryId = $productCategoryId;

        return $this;
    }

    public function getProductPaymentId(): ?int
    {
        return $this->productPaymentId;
    }

    public function setProductPaymentId(?int $productPaymentId): self
    {
        $this->productPaymentId = $productPaymentId;

        return $this;
    }

    public function getFormId(): ?int
    {
        return $this->formId;
    }

    public function setFormId(?int $formId): self
    {
        $this->formId = $formId;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUnit(): string
    {
        return $this->unit;
    }

    public function setUnit(string $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isHidden(): bool
    {
        return $this->hidden;
    }

    public function setHidden(bool $hidden): self
    {
        $this->hidden = $hidden;

        return $this;
    }

    public function isAddon(): bool
    {
        return $this->isAddon;
    }

    public function setIsAddon(bool $isAddon): self
    {
        $this->isAddon = $isAddon;

        return $this;
    }

    public function getSetup(): string
    {
        return $this->setup;
    }

    public function setSetup(string $setup): self
    {
        $this->setup = $setup;

        return $this;
    }

    public function getAddons(): ?string
    {
        return $this->addons;
    }

    public function setAddons(?string $addons): self
    {
        $this->addons = $addons;

        return $this;
    }

    public function getIconUrl(): ?string
    {
        return $this->iconUrl;
    }

    public function setIconUrl(?string $iconUrl): self
    {
        $this->iconUrl = $iconUrl;

        return $this;
    }

    public function isAllowQuantitySelect(): bool
    {
        return $this->allowQuantitySelect;
    }

    public function setAllowQuantitySelect(bool $allowQuantitySelect): self
    {
        $this->allowQuantitySelect = $allowQuantitySelect;

        return $this;
    }

    public function isStockControl(): bool
    {
        return $this->stockControl;
    }

    public function setStockControl(bool $stockControl): self
    {
        $this->stockControl = $stockControl;

        return $this;
    }

    public function getQuantityInStock(): int
    {
        return $this->quantityInStock;
    }

    public function setQuantityInStock(int $quantityInStock): self
    {
        $this->quantityInStock = $quantityInStock;

        return $this;
    }

    public function getPlugin(): ?string
    {
        return $this->plugin;
    }

    public function setPlugin(?string $plugin): self
    {
        $this->plugin = $plugin;

        return $this;
    }

    public function getPluginConfig(): ?string
    {
        return $this->pluginConfig;
    }

    public function setPluginConfig(?string $pluginConfig): self
    {
        $this->pluginConfig = $pluginConfig;

        return $this;
    }

    public function getUpgrades(): ?string
    {
        return $this->upgrades;
    }

    public function setUpgrades(?string $upgrades): self
    {
        $this->upgrades = $upgrades;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getConfig(): ?string
    {
        return $this->config;
    }

    public function setConfig(?string $config): self
    {
        $this->config = $config;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
}
