<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Product\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Product\Repository\PromoRepository::class)]
#[ORM\Table(name: 'promo')]
#[ORM\HasLifecycleCallbacks]
class Promo implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    final public const string ABSOLUTE = 'absolute';
    final public const string PERCENTAGE = 'percentage';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 100, nullable: true)]
    private ?string $code = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 30, options: ['default' => 'percentage'])]
    private string $type = 'percentage';

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $value = null;

    #[ORM\Column(name: 'maxuses', type: \Doctrine\DBAL\Types\Types::INTEGER, nullable: true, options: ['default' => 0])]
    /** @phpstan-ignore property.unusedType (column is nullable in the DB) */
    private ?int $maxUses = 0;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER, nullable: true, options: ['default' => 0])]
    /** @phpstan-ignore property.unusedType (column is nullable in the DB) */
    private ?int $used = 0;

    #[ORM\Column(name: 'freesetup', type: \Doctrine\DBAL\Types\Types::BOOLEAN, nullable: true, options: ['default' => false])]
    /** @phpstan-ignore property.unusedType (column is nullable in the DB) */
    private ?bool $freeSetup = false;

    #[ORM\Column(name: 'once_per_client', type: \Doctrine\DBAL\Types\Types::BOOLEAN, nullable: true, options: ['default' => false])]
    /** @phpstan-ignore property.unusedType (column is nullable in the DB) */
    private ?bool $oncePerClient = false;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN, nullable: true, options: ['default' => false])]
    /** @phpstan-ignore property.unusedType (column is nullable in the DB) */
    private ?bool $recurring = false;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN, nullable: true, options: ['default' => false])]
    /** @phpstan-ignore property.unusedType (column is nullable in the DB) */
    private ?bool $active = false;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $products = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $periods = null;

    #[ORM\Column(name: 'client_groups', type: \Doctrine\DBAL\Types\Types::TEXT, nullable: true)]
    private ?string $clientGroups = null;

    #[ORM\Column(name: 'start_at', type: \Doctrine\DBAL\Types\Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $startAt = null;

    #[ORM\Column(name: 'end_at', type: \Doctrine\DBAL\Types\Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $endAt = null;

    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'code' => $this->code,
            'description' => $this->description,
            'type' => $this->type,
            'value' => $this->value !== null ? (float) $this->value : null,
            'maxuses' => $this->maxUses ?? 0,
            'used' => $this->used ?? 0,
            'freesetup' => $this->freeSetup ?? false,
            'once_per_client' => $this->oncePerClient ?? false,
            'recurring' => $this->recurring ?? false,
            'active' => $this->active ?? false,
            'products' => $this->products,
            'periods' => $this->periods,
            'client_groups' => $this->clientGroups,
            'start_at' => $this->startAt?->format('Y-m-d H:i:s'),
            'end_at' => $this->endAt?->format('Y-m-d H:i:s'),
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getValue(): ?float
    {
        return $this->value !== null ? (float) $this->value : null;
    }

    public function setValue(float|int|string|null $value): self
    {
        $this->value = $value !== null ? sprintf('%.2f', (float) $value) : null;

        return $this;
    }

    public function getMaxUses(): int
    {
        return $this->maxUses ?? 0;
    }

    public function setMaxUses(?int $maxUses): self
    {
        $this->maxUses = max(0, $maxUses ?? 0);

        return $this;
    }

    public function getUsed(): int
    {
        return $this->used ?? 0;
    }

    public function setUsed(?int $used): self
    {
        $this->used = max(0, $used ?? 0);

        return $this;
    }

    public function isFreeSetup(): bool
    {
        return $this->freeSetup ?? false;
    }

    public function setFreeSetup(bool $freeSetup): self
    {
        $this->freeSetup = $freeSetup;

        return $this;
    }

    public function isOncePerClient(): bool
    {
        return $this->oncePerClient ?? false;
    }

    public function setOncePerClient(bool $oncePerClient): self
    {
        $this->oncePerClient = $oncePerClient;

        return $this;
    }

    public function isRecurring(): bool
    {
        return $this->recurring ?? false;
    }

    public function setRecurring(bool $recurring): self
    {
        $this->recurring = $recurring;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->active ?? false;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getProducts(): ?string
    {
        return $this->products;
    }

    public function setProducts(?string $products): self
    {
        $this->products = $products;

        return $this;
    }

    public function getPeriods(): ?string
    {
        return $this->periods;
    }

    public function setPeriods(?string $periods): self
    {
        $this->periods = $periods;

        return $this;
    }

    public function getClientGroups(): ?string
    {
        return $this->clientGroups;
    }

    public function setClientGroups(?string $clientGroups): self
    {
        $this->clientGroups = $clientGroups;

        return $this;
    }

    public function getStartAt(): ?\DateTime
    {
        return $this->startAt;
    }

    public function setStartAt(?\DateTime $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?\DateTime
    {
        return $this->endAt;
    }

    public function setEndAt(?\DateTime $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }
}
