<?php

declare(strict_types=1);

namespace Box\Mod\Order\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Core\Doctrine\TimestampInterface;
use FOSSBilling\Core\Doctrine\TimestampTrait;

#[ORM\Entity(repositoryClass: \Box\Mod\Order\Repository\OrderRepository::class)]
#[ORM\Table(name: 'client_order')]
#[ORM\Index(name: 'client_order_client_id_idx', columns: ['client_id'])]
#[ORM\Index(name: 'client_order_product_id_idx', columns: ['product_id'])]
#[ORM\Index(name: 'client_order_form_id_idx', columns: ['form_id'])]
#[ORM\Index(name: 'client_order_promo_id_idx', columns: ['promo_id'])]
#[ORM\Index(name: 'client_order_status_expires_at_idx', columns: ['status', 'expires_at'])]
#[ORM\Index(name: 'client_order_unpaid_invoice_id_idx', columns: ['unpaid_invoice_id'])]
#[ORM\HasLifecycleCallbacks]
class Order implements TimestampInterface
{
    use TimestampTrait;

    final public const string STATUS_PENDING_SETUP = 'pending_setup';
    final public const string STATUS_FAILED_SETUP = 'failed_setup';
    final public const string STATUS_FAILED_RENEW = 'failed_renew';
    final public const string STATUS_ACTIVE = 'active';
    final public const string STATUS_CANCELED = 'canceled';
    final public const string STATUS_SUSPENDED = 'suspended';

    final public const string ACTION_CREATE = 'create';
    final public const string ACTION_ACTIVATE = 'activate';
    final public const string ACTION_RENEW = 'renew';
    final public const string ACTION_SUSPEND = 'suspend';
    final public const string ACTION_UNSUSPEND = 'unsuspend';
    final public const string ACTION_CANCEL = 'cancel';
    final public const string ACTION_UNCANCEL = 'uncancel';
    final public const string ACTION_DELETE = 'delete';

    public static function getValidStatuses(): array
    {
        return [
            self::STATUS_PENDING_SETUP,
            self::STATUS_FAILED_SETUP,
            self::STATUS_FAILED_RENEW,
            self::STATUS_ACTIVE,
            self::STATUS_CANCELED,
            self::STATUS_SUSPENDED,
        ];
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'product_id', type: Types::BIGINT, nullable: true)]
    private ?int $productId = null;

    #[ORM\Column(name: 'form_id', type: Types::BIGINT, nullable: true)]
    private ?int $formId = null;

    #[ORM\Column(name: 'promo_id', type: Types::BIGINT, nullable: true)]
    private ?int $promoId = null;

    #[ORM\Column(name: 'promo_recurring', type: Types::BOOLEAN, nullable: true)]
    private ?bool $promoRecurring = null;

    #[ORM\Column(name: 'promo_used', type: Types::BIGINT, nullable: true)]
    private ?int $promoUsed = null;

    #[ORM\Column(name: 'group_id', type: Types::STRING, length: 255, nullable: true)]
    private ?string $groupId = null;

    #[ORM\Column(name: 'group_master', type: Types::BOOLEAN, nullable: true, options: ['default' => false])]
    private ?bool $groupMaster = false;

    #[ORM\Column(name: 'invoice_option', type: Types::STRING, length: 255, nullable: true)]
    private ?string $invoiceOption = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true)]
    private ?string $currency = null;

    #[ORM\Column(name: 'unpaid_invoice_id', type: Types::BIGINT, nullable: true)]
    private ?int $unpaidInvoiceId = null;

    #[ORM\Column(name: 'service_id', type: Types::BIGINT, nullable: true)]
    private ?int $serviceId = null;

    #[ORM\Column(name: 'service_type', type: Types::STRING, length: 100, nullable: true)]
    private ?string $serviceType = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true)]
    private ?string $period = null;

    #[ORM\Column(type: Types::BIGINT, nullable: true, options: ['default' => 1])]
    private ?int $quantity = 1;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $unit = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $price = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2, nullable: true)]
    private ?string $discount = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $reason = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $config = null;

    #[ORM\Column(name: 'suspension_grace_days', type: Types::INTEGER, nullable: true)]
    private ?int $suspensionGraceDays = null;

    #[ORM\Column(name: 'referred_by', type: Types::STRING, length: 255, nullable: true)]
    private ?string $referredBy = null;

    #[ORM\Column(name: 'expires_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $expiresAt = null;

    #[ORM\Column(name: 'activated_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $activatedAt = null;

    #[ORM\Column(name: 'suspended_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $suspendedAt = null;

    #[ORM\Column(name: 'unsuspended_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $unsuspendedAt = null;

    #[ORM\Column(name: 'canceled_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $canceledAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->productId;
    }

    public function setProductId(?int $productId): self
    {
        $this->productId = $productId;

        return $this;
    }

    public function getFormId(): ?int
    {
        return $this->formId;
    }

    public function setFormId(?int $formId): self
    {
        $this->formId = $formId;

        return $this;
    }

    public function getPromoId(): ?int
    {
        return $this->promoId;
    }

    public function setPromoId(?int $promoId): self
    {
        $this->promoId = $promoId;

        return $this;
    }

    public function isPromoRecurring(): ?bool
    {
        return $this->promoRecurring;
    }

    public function setPromoRecurring(?bool $promoRecurring): self
    {
        $this->promoRecurring = $promoRecurring;

        return $this;
    }

    public function getPromoUsed(): ?int
    {
        return $this->promoUsed;
    }

    public function setPromoUsed(?int $promoUsed): self
    {
        $this->promoUsed = $promoUsed;

        return $this;
    }

    public function getGroupId(): ?string
    {
        return $this->groupId;
    }

    public function setGroupId(?string $groupId): self
    {
        $this->groupId = $groupId;

        return $this;
    }

    public function isGroupMaster(): bool
    {
        return (bool) $this->groupMaster;
    }

    public function setGroupMaster(?bool $groupMaster): self
    {
        $this->groupMaster = $groupMaster;

        return $this;
    }

    public function getInvoiceOption(): ?string
    {
        return $this->invoiceOption;
    }

    public function setInvoiceOption(?string $invoiceOption): self
    {
        $this->invoiceOption = $invoiceOption;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getUnpaidInvoiceId(): ?int
    {
        return $this->unpaidInvoiceId;
    }

    public function setUnpaidInvoiceId(?int $unpaidInvoiceId): self
    {
        $this->unpaidInvoiceId = $unpaidInvoiceId;

        return $this;
    }

    public function getServiceId(): ?int
    {
        return $this->serviceId;
    }

    public function setServiceId(?int $serviceId): self
    {
        $this->serviceId = $serviceId;

        return $this;
    }

    public function getServiceType(): ?string
    {
        return $this->serviceType;
    }

    public function setServiceType(?string $serviceType): self
    {
        $this->serviceType = $serviceType;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(?string $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string|int|float|null $price): self
    {
        $this->price = $price === null ? null : (string) $price;

        return $this;
    }

    public function getDiscount(): ?string
    {
        return $this->discount;
    }

    public function setDiscount(string|int|float|null $discount): self
    {
        $this->discount = $discount === null ? null : (string) $discount;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(?string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getConfig(): ?string
    {
        return $this->config;
    }

    public function setConfig(?string $config): self
    {
        $this->config = $config;

        return $this;
    }

    public function getSuspensionGraceDays(): ?int
    {
        return $this->suspensionGraceDays;
    }

    public function setSuspensionGraceDays(?int $suspensionGraceDays): self
    {
        $this->suspensionGraceDays = $suspensionGraceDays;

        return $this;
    }

    public function getReferredBy(): ?string
    {
        return $this->referredBy;
    }

    public function setReferredBy(?string $referredBy): self
    {
        $this->referredBy = $referredBy;

        return $this;
    }

    public function getExpiresAt(): ?\DateTime
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(?\DateTime $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }

    public function getActivatedAt(): ?\DateTime
    {
        return $this->activatedAt;
    }

    public function setActivatedAt(?\DateTime $activatedAt): self
    {
        $this->activatedAt = $activatedAt;

        return $this;
    }

    public function getSuspendedAt(): ?\DateTime
    {
        return $this->suspendedAt;
    }

    public function setSuspendedAt(?\DateTime $suspendedAt): self
    {
        $this->suspendedAt = $suspendedAt;

        return $this;
    }

    public function getUnsuspendedAt(): ?\DateTime
    {
        return $this->unsuspendedAt;
    }

    public function setUnsuspendedAt(?\DateTime $unsuspendedAt): self
    {
        $this->unsuspendedAt = $unsuspendedAt;

        return $this;
    }

    public function getCanceledAt(): ?\DateTime
    {
        return $this->canceledAt;
    }

    public function setCanceledAt(?\DateTime $canceledAt): self
    {
        $this->canceledAt = $canceledAt;

        return $this;
    }
}
