<?php

declare(strict_types=1);

namespace Box\Mod\Order\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Order\Repository\OrderStatusRepository::class)]
#[ORM\Table(name: 'client_order_status')]
#[ORM\Index(name: 'client_order_id_idx', columns: ['client_order_id'])]
#[ORM\HasLifecycleCallbacks]
class OrderStatus implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_order_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientOrderId = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientOrderId(): ?int
    {
        return $this->clientOrderId;
    }

    public function setClientOrderId(?int $clientOrderId): self
    {
        $this->clientOrderId = $clientOrderId;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }
}
