{% block subject %}[{{ guest.system_company.name }}] {{ order.title }} Reactivated{% endblock %}
{% block content %}
{% apply markdown %}

Hello {{ c.first_name }} {{ c.last_name }},

Your *{{ order.title }}* has been reactivated. 

Login to members area: {{'login'|link({'email' : c.email }) }}
Manage order: {{ 'order/service/manage'|link }}/{{ order.id }}

{{ guest.system_company.signature }}

{% endapply %}
{% endblock %}
