{% block subject %}[{{ guest.system_company.name }}] Radio Control Panel Activated{% endblock %}
{% block content %}
{% apply markdown %}
Hello {{ c.first_name }} {{ c.last_name }},

Your Centova Cast credentials:
 
Username: {{username}}     
Password: {{adminpassword}}

Password to connect to the stream: {{ sourcepassword }}   

Control panel link: {{ server.url }}  

{{ guest.system_company.signature }}

{% endapply %}
{% endblock %}
