<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Support\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;
use FOSSBilling\Tools;

#[ORM\Entity(repositoryClass: \Box\Mod\Support\Repository\HelpdeskRepository::class)]
#[ORM\Table(name: 'support_helpdesk')]
#[ORM\HasLifecycleCallbacks]
class Helpdesk implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(name: 'can_reopen', type: Types::BOOLEAN, nullable: true)]
    private ?bool $canReopen = null;

    #[ORM\Column(name: 'close_after', type: Types::SMALLINT, nullable: true, options: ['default' => 24])]
    private ?int $closeAfter = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $signature = null;

    /**
     * @var Collection<int, SupportTicket>
     */
    #[ORM\OneToMany(mappedBy: 'helpdesk', targetEntity: SupportTicket::class)]
    private Collection $tickets;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function toApiArray(\Box\Mod\Client\Entity\Client|\Box\Mod\Staff\Entity\Admin|\FOSSBilling\Identity\Guest|null $identity = null): array
    {
        if ($identity instanceof \Box\Mod\Staff\Entity\Admin) {
            return [
                'id' => $this->id,
                'name' => $this->name,
                'email' => $this->email,
                'can_reopen' => $this->canReopen,
                'close_after' => $this->closeAfter,
                'signature' => $this->signature,
                'created_at' => $this->createdAt?->format('Y-m-d H:i:s'),
                'updated_at' => $this->updatedAt?->format('Y-m-d H:i:s'),
            ];
        }

        return [
            'id' => $this->id,
            'name' => $this->name,
            'can_reopen' => (bool) $this->canReopen,
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function canReopen(): bool
    {
        return (bool) $this->canReopen;
    }

    public function setCanReopen(mixed $canReopen): self
    {
        $this->canReopen = $canReopen === null ? null : Tools::normalizeBoolean($canReopen);

        return $this;
    }

    public function getCloseAfter(): ?int
    {
        return $this->closeAfter;
    }

    public function setCloseAfter(int|string|null $closeAfter): self
    {
        $this->closeAfter = $closeAfter === null || $closeAfter === '' ? null : (int) $closeAfter;

        return $this;
    }

    public function getSignature(): ?string
    {
        return $this->signature;
    }

    public function setSignature(?string $signature): self
    {
        $this->signature = $signature;

        return $this;
    }

    /**
     * @return Collection<int, SupportTicket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }
}
