<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * Copyright 2011-2021 BoxBilling, Inc.
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Support\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Support\Repository\KbArticleRepository::class)]
#[ORM\Table(name: 'support_kb_article')]
#[ORM\HasLifecycleCallbacks]
class KbArticle implements ApiArrayInterface, TimestampInterface
{
    final public const string ACTIVE = 'active';
    final public const string DRAFT = 'draft';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: KbArticleCategory::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(name: 'kb_article_category_id', referencedColumnName: 'id', nullable: true)]
    private ?KbArticleCategory $category = null;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $views = 0;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::STRING, length: 30, options: ['default' => self::ACTIVE])]
    private string $status = self::ACTIVE;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $createdAt = null;

    #[ORM\Column(name: 'updated_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $updatedAt = null;

    public function toApiArray(\Model_Admin|\Model_Client|\Model_Guest|null $identity = null, bool $deep = false): array
    {
        $category = $this->category;
        if (!$category instanceof KbArticleCategory) {
            throw new \FOSSBilling\Exception('Knowledge Base category not found');
        }

        $data = [
            'id' => $this->id,
            'slug' => $this->slug,
            'title' => $this->title,
            'views' => $this->views,
            'created_at' => $this->createdAt?->format('Y-m-d H:i:s'),
            'status' => $this->status,
            'updated_at' => $this->updatedAt?->format('Y-m-d H:i:s'),
            'category' => [
                'id' => $category->getId(),
                'slug' => $category->getSlug(),
                'title' => $category->getTitle(),
            ],
        ];

        if ($deep) {
            $data['content'] = $this->content;
        }

        if ($identity instanceof \Model_Admin) {
            $data['status'] = $this->status;
            $data['kb_article_category_id'] = $this->getKbArticleCategoryId();
        }

        return $data;
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTime();
        $this->createdAt ??= $now;
        $this->updatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function updateTimestamp(): void
    {
        $this->updatedAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKbArticleCategoryId(): ?int
    {
        return $this->category?->getId();
    }

    public function getCategory(): ?KbArticleCategory
    {
        return $this->category;
    }

    public function setCategory(?KbArticleCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getViews(): int
    {
        return $this->views;
    }

    public function setViews(?int $views): self
    {
        $this->views = max(0, (int) ($views ?? 0));

        return $this;
    }

    public function incrementViews(): self
    {
        ++$this->views;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function matchesSearch(string $query): bool
    {
        return stripos($this->title ?? '', $query) !== false || stripos($this->content ?? '', $query) !== false;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
}
