<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Support\Entity;

use Box\Mod\Support\Repository\SupportTicketMessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * A message in a support ticket thread. One ticket has many messages, ordered
 * by `id` ASC (FIFO). The owning ticket is a `ManyToOne` association since
 * both entities live in the Support module.
 */
#[ORM\Entity(repositoryClass: SupportTicketMessageRepository::class)]
#[ORM\Table(name: 'support_ticket_message')]
#[ORM\Index(name: 'idx_msg_ticket', columns: ['support_ticket_id'])]
#[ORM\HasLifecycleCallbacks]
class SupportTicketMessage implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: SupportTicket::class, inversedBy: 'messages')]
    #[ORM\JoinColumn(name: 'support_ticket_id', referencedColumnName: 'id', nullable: true, onDelete: 'CASCADE')]
    private ?SupportTicket $ticket = null;

    #[ORM\Column(name: 'client_id', type: Types::INTEGER, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'admin_id', type: Types::INTEGER, nullable: true)]
    private ?int $adminId = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $attachment = null;

    #[ORM\Column(type: Types::STRING, length: 45, nullable: true)]
    private ?string $ip = null;

    public function toApiArray(\Model_Admin|\Model_Client|\Model_Guest|null $identity = null): array
    {
        if ($identity instanceof \Model_Admin) {
            return [
                'id' => $this->id,
                'support_ticket_id' => $this->ticket?->getId(),
                'client_id' => $this->clientId,
                'admin_id' => $this->adminId,
                'content' => $this->content,
                'attachment' => $this->attachment,
                'ip' => $this->ip,
                'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
                'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
            ];
        }

        return [
            'id' => $this->id,
            'content' => $this->content,
            'attachment' => $this->attachment,
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTicket(): ?SupportTicket
    {
        return $this->ticket;
    }

    public function setTicket(?SupportTicket $ticket): self
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function getSupportTicket(): ?SupportTicket
    {
        return $this->ticket;
    }

    public function setSupportTicket(?SupportTicket $ticket): self
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function getSupportTicketId(): ?int
    {
        return $this->ticket?->getId();
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getAdminId(): ?int
    {
        return $this->adminId;
    }

    public function setAdminId(?int $adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAttachment(): ?string
    {
        return $this->attachment;
    }

    public function setAttachment(?string $attachment): self
    {
        $this->attachment = $attachment;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }
}
