<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Support\Entity;

use Box\Mod\Support\Repository\SupportTicketNoteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * An internal note on a support ticket — visible to staff but not to the
 * client. One ticket has many notes.
 */
#[ORM\Entity(repositoryClass: SupportTicketNoteRepository::class)]
#[ORM\Table(name: 'support_ticket_note')]
#[ORM\Index(name: 'idx_note_ticket', columns: ['support_ticket_id'])]
#[ORM\HasLifecycleCallbacks]
class SupportTicketNote implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: SupportTicket::class, inversedBy: 'notes')]
    #[ORM\JoinColumn(name: 'support_ticket_id', referencedColumnName: 'id', nullable: true, onDelete: 'CASCADE')]
    private ?SupportTicket $ticket = null;

    #[ORM\Column(name: 'admin_id', type: Types::INTEGER, nullable: true)]
    private ?int $adminId = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $note = null;

    public function toApiArray(\Model_Admin|\Model_Client|\Model_Guest|null $identity = null): array
    {
        return [
            'id' => $this->id,
            'support_ticket_id' => $this->ticket?->getId(),
            'admin_id' => $this->adminId,
            'note' => $this->note,
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTicket(): ?SupportTicket
    {
        return $this->ticket;
    }

    public function setTicket(?SupportTicket $ticket): self
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function getSupportTicket(): ?SupportTicket
    {
        return $this->ticket;
    }

    public function setSupportTicket(?SupportTicket $ticket): self
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function getSupportTicketId(): ?int
    {
        return $this->ticket?->getId();
    }

    public function getAdminId(): ?int
    {
        return $this->adminId;
    }

    public function setAdminId(?int $adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }
}
