<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Support\Entity;

use Box\Mod\Support\Repository\SupportTicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * A support ticket. Cross-module fields (Client, Helpdesk FK) are stored as
 * plain nullable IDs to keep this module decoupled from the Client migration
 * and from the (already-migrated) Helpdesk entity.
 */
#[ORM\Entity(repositoryClass: SupportTicketRepository::class)]
#[ORM\Table(name: 'support_ticket')]
#[ORM\Index(name: 'idx_ticket_status', columns: ['status'])]
#[ORM\Index(name: 'idx_ticket_client', columns: ['client_id'])]
#[ORM\HasLifecycleCallbacks]
class SupportTicket implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    public const STATUS_OPEN = 'open';
    public const STATUS_ONHOLD = 'on_hold';
    public const STATUS_CLOSED = 'closed';

    public const REL_TYPE_ORDER = 'order';

    public const REL_STATUS_PENDING = 'pending';
    public const REL_STATUS_COMPLETE = 'complete';

    public const REL_TASK_CANCEL = 'cancel';
    public const REL_TASK_UPGRADE = 'upgrade';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Helpdesk::class, inversedBy: 'tickets')]
    #[ORM\JoinColumn(name: 'support_helpdesk_id', referencedColumnName: 'id', nullable: true)]
    private ?Helpdesk $helpdesk = null;

    #[ORM\Column(name: 'client_id', type: Types::INTEGER, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'access_hash', type: Types::STRING, length: 255, nullable: true)]
    private ?string $accessHash = null;

    #[ORM\Column(name: 'author_name', type: Types::STRING, length: 255, nullable: true)]
    private ?string $authorName = null;

    #[ORM\Column(name: 'author_email', type: Types::STRING, length: 255, nullable: true)]
    private ?string $authorEmail = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true, options: ['default' => 100])]
    private ?int $priority = 100;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::STRING, length: 30, nullable: true, options: ['default' => self::STATUS_OPEN])]
    private ?string $status = self::STATUS_OPEN;

    #[ORM\Column(name: 'rel_type', type: Types::STRING, length: 100, nullable: true)]
    private ?string $relType = null;

    #[ORM\Column(name: 'rel_id', type: Types::INTEGER, nullable: true)]
    private ?int $relId = null;

    #[ORM\Column(name: 'rel_task', type: Types::STRING, length: 100, nullable: true)]
    private ?string $relTask = null;

    #[ORM\Column(name: 'rel_new_value', type: Types::TEXT, nullable: true)]
    private ?string $relNewValue = null;

    #[ORM\Column(name: 'rel_status', type: Types::STRING, length: 100, nullable: true)]
    private ?string $relStatus = null;

    /**
     * @var Collection<int, SupportTicketMessage>
     */
    #[ORM\OneToMany(mappedBy: 'ticket', targetEntity: SupportTicketMessage::class)]
    #[ORM\OrderBy(['id' => 'ASC'])]
    private Collection $messages;

    /**
     * @var Collection<int, SupportTicketNote>
     */
    #[ORM\OneToMany(mappedBy: 'ticket', targetEntity: SupportTicketNote::class)]
    private Collection $notes;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function toApiArray(\Model_Admin|\Model_Client|\Model_Guest|null $identity = null): array
    {
        $data = [
            'id' => $this->id,
            'support_helpdesk_id' => $this->helpdesk?->getId(),
            'client_id' => $this->clientId,
            'access_hash' => $this->accessHash,
            'author_name' => $this->authorName,
            'author_email' => $this->authorEmail,
            'priority' => $this->priority,
            'subject' => $this->subject,
            'status' => $this->status,
            'rel_type' => $this->relType,
            'rel_id' => $this->relId,
            'rel_task' => $this->relTask,
            'rel_new_value' => $this->relNewValue,
            'rel_status' => $this->relStatus,
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
            'updated_at' => $this->getUpdatedAt()?->format('Y-m-d H:i:s'),
        ];

        if (!empty($data['access_hash'])) {
            $data['hash'] = $data['access_hash'];
        }

        if ($identity instanceof \Model_Admin) {
            return $data;
        }

        unset(
            $data['support_helpdesk_id'],
            $data['client_id'],
            $data['priority'],
            $data['access_hash'],
            $data['rel_type'],
            $data['rel_id'],
            $data['rel_task'],
            $data['rel_new_value'],
            $data['rel_status'],
        );

        return $data;
    }

    /**
     * A ticket belongs to a guest when it has no client but does carry a
     * public access hash (used by the guest/public ticket flow).
     */
    public function isGuestTicket(): bool
    {
        return $this->clientId === null && $this->accessHash !== null;
    }

    /**
     * Whether a closed ticket may be re-opened.
     *
     * Non-closed tickets can always be re-opened. Closed tickets delegate to
     * their helpdesk's `can_reopen` flag. Throws if the helpdesk cannot be
     * resolved, matching the legacy behaviour.
     */
    public function canBeReopen(): bool
    {
        if ($this->status !== self::STATUS_CLOSED) {
            return true;
        }

        $helpdesk = $this->helpdesk;
        if (!$helpdesk instanceof Helpdesk) {
            throw new \FOSSBilling\Exception('Helpdesk invalid');
        }

        return $helpdesk->canReopen();
    }

    public function close(): self
    {
        $this->status = self::STATUS_CLOSED;

        return $this;
    }

    public function markTaskComplete(): self
    {
        $this->relStatus = self::REL_STATUS_COMPLETE;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHelpdesk(): ?Helpdesk
    {
        return $this->helpdesk;
    }

    public function setHelpdesk(?Helpdesk $helpdesk): self
    {
        $this->helpdesk = $helpdesk;

        return $this;
    }

    public function getSupportHelpdeskId(): ?int
    {
        return $this->helpdesk?->getId();
    }

    public function setSupportHelpdesk(?Helpdesk $helpdesk): self
    {
        $this->helpdesk = $helpdesk;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getAccessHash(): ?string
    {
        return $this->accessHash;
    }

    public function setAccessHash(?string $accessHash): self
    {
        $this->accessHash = $accessHash;

        return $this;
    }

    public function getAuthorName(): ?string
    {
        return $this->authorName;
    }

    public function setAuthorName(?string $authorName): self
    {
        $this->authorName = $authorName;

        return $this;
    }

    public function getAuthorEmail(): ?string
    {
        return $this->authorEmail;
    }

    public function setAuthorEmail(?string $authorEmail): self
    {
        $this->authorEmail = $authorEmail;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getRelType(): ?string
    {
        return $this->relType;
    }

    public function setRelType(?string $relType): self
    {
        $this->relType = $relType;

        return $this;
    }

    public function getRelId(): ?int
    {
        return $this->relId;
    }

    public function setRelId(?int $relId): self
    {
        $this->relId = $relId;

        return $this;
    }

    public function getRelTask(): ?string
    {
        return $this->relTask;
    }

    public function setRelTask(?string $relTask): self
    {
        $this->relTask = $relTask;

        return $this;
    }

    public function getRelNewValue(): ?string
    {
        return $this->relNewValue;
    }

    public function setRelNewValue(?string $relNewValue): self
    {
        $this->relNewValue = $relNewValue;

        return $this;
    }

    public function getRelStatus(): ?string
    {
        return $this->relStatus;
    }

    public function setRelStatus(?string $relStatus): self
    {
        $this->relStatus = $relStatus;

        return $this;
    }

    /**
     * @return Collection<int, SupportTicketMessage>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    /**
     * @return Collection<int, SupportTicketNote>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }
}
