<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Support\Entity;

use Box\Mod\Support\Repository\SupportTicketMessageHistoryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Interfaces\ApiArrayInterface;
use FOSSBilling\Interfaces\TimestampInterface;

/**
 * A snapshot of a support ticket message's content taken immediately before an
 * admin edit overwrites it, so the original wording is never lost. One
 * message can have many history rows, one per edit.
 */
#[ORM\Entity(repositoryClass: SupportTicketMessageHistoryRepository::class)]
#[ORM\Table(name: 'support_ticket_message_history')]
#[ORM\Index(name: 'idx_msg_history_message', columns: ['support_ticket_message_id'])]
#[ORM\HasLifecycleCallbacks]
class SupportTicketMessageHistory implements ApiArrayInterface, TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: SupportTicketMessage::class)]
    #[ORM\JoinColumn(name: 'support_ticket_message_id', referencedColumnName: 'id', nullable: false, onDelete: 'CASCADE')]
    private ?SupportTicketMessage $message = null;

    #[ORM\Column(name: 'admin_id', type: Types::INTEGER, nullable: true)]
    private ?int $adminId = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    public function toApiArray(\Model_Admin|\Model_Client|\Model_Guest|null $identity = null): array
    {
        return [
            'id' => $this->id,
            'support_ticket_message_id' => $this->message?->getId(),
            'admin_id' => $this->adminId,
            'content' => $this->content,
            'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?SupportTicketMessage
    {
        return $this->message;
    }

    public function setMessage(?SupportTicketMessage $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getAdminId(): ?int
    {
        return $this->adminId;
    }

    public function setAdminId(?int $adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }
}
