{% extends "layout_default.phtml" %}

{% block meta_title %}{{ 'Error'|trans }}{% endblock %}

{% block content_before %}
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">404</h1>
            <ol class="breadcrumb">
                <li><a href="{{ ''|link }}">{{ 'Home'|trans }}</a></li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>{{ 'Looks like we have a misunderstanding here'|trans }}</h1>
	<p>{{ exception.getMessage }}</p>
</div>
{% endblock %}
