{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{{ 'Reset password'|trans }}{% endblock %}

{% block content_before %}
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ 'Reset password'|trans }}</h1>
            <ol class="breadcrumb">
                <li><a href="{{''|link }}">{{ 'Home'|trans }}</a></li>
                <li class="active">{{ 'Reset password'|trans }}</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
{% endblock %}

{% block content %}
    <!--<form action="" method="post" id="password-reset" class="form-inline">-->
    <form method="post" action="" class="api_form form-inline" data-api-url="guest/client/reset_password" data-api-msg="{{ 'Password reset confirmation email was sent'|trans }}">
        <legend>{{ 'Enter your email to reset password. You will receive new password after reset link is confirmed.'|trans }}</legend>
        <div class="form-group">
            <label for="exampleInputName2">{{ 'Email Address'|trans }}:</label>
            <input type="email" class="form-control" name="email" value="{{ request.email }}" required="required">
        </div>
        <input class="btn btn-warning" type="submit" value="{{ 'Reset password'|trans }}">
    </form>
{% endblock %}

{% block js %}
<script>
    $(function() {
        $('#password-reset').bind('submit', function(event) {
            bb.post(
                'guest/client/reset_password',
                $(this).serialize(),
                function(result) {
                    bb.msg("{{ 'Password reset confirmation email was sent'|trans }}");
                }
            );

            return false;
        });
    });
</script>
{% endblock %}