{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% block meta_title %}{{ 'Privacy Policy'|trans }}{% endblock %}

{% block content_before %}
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ company.name }} {{ 'Privacy Policy'|trans }}</h1>
				<ol class="breadcrumb">
					<li><a href="{{''|link }}">{{ 'Home'|trans }}</a></li>
					<li class="active">{{ company.name }} {{ 'Privacy Policy'|trans }}</li>
				</ol>
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

	{{ company.privacy_policy|bbmd }}

{% endblock %}