{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{{ 'Profile details'|trans }}{% endblock %}

{% import "macro_functions.phtml" as mf %}

{% set profile = client.client_get %}

{% block content_before %}
	<!-- Page Heading/Breadcrumbs -->
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">{{ 'Profile details'|trans }}
				<small>{{ 'Keep your profile up to date'|trans }}</small>
			</h1>
		</div>
	</div>
	<!-- /.row -->
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<ul id="myTab" class="nav nav-tabs nav-justified">
				<li class="active"><a href="#tab-details" data-toggle="tab"><i class="fa fa-user"></i> {{ 'Details'|trans }}</a></li>
				<li><a href="#tab-password" data-toggle="tab"><i class="fa fa-key"></i> {{ 'Password'|trans }}</a></li>
				<li><a href="#tab-gravatar" data-toggle="tab"><i class="fa fa-camera"></i> {{ 'Gravatar'|trans }}</a></li>
				<li><a href="#tab-currency" data-toggle="tab"><i class="fa fa-money"></i> {{ 'Currency'|trans }}</a></li>
				<li><a href="#tab-api" data-toggle="tab"><i class="fa fa-plug"></i> {{ 'API'|trans }}</a></li>
			</ul>

			<div id="myTabContent" class="tab-content">
				<div class="tab-pane fade active in" id="tab-details">
					<h4>{{ 'Update profile'|trans }}</h4>
					<form method="post" action="" class="api_form" data-api-url="client/client/update" data-api-msg="{{ 'Profile updated'|trans }}">
					<div class="well row">
						<div class="col-md-6">
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Email Address'|trans }}:</label>
										<input type="email" class="form-control" name="email" value="{{ profile.email }}" required="required">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'First Name'|trans }}:</label>
										<input type="text" class="form-control" name="first_name" value="{{ profile.first_name }}" required="required">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Last Name'|trans }}:</label>
										<input type="text" class="form-control" name="last_name" value="{{ profile.last_name }}" required="required">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Company Name'|trans }}:</label>
										<input type="text" class="form-control" name="company" value="{{ profile.company }}">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Phone Country Code'|trans }}:</label>
										<input type="text" class="form-control" name="phone_cc" value="{{ profile.phone_cc }}" required="required">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Phone Number'|trans }}:</label>
										<input type="text" class="form-control" name="phone" value="{{ profile.phone }}" required="required">
									</div>
								</div>
								
						</div>
						<div class="col-md-6">
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Address'|trans }}:</label>
										<input type="text" class="form-control" name="address_1" value="{{ profile.address_1 }}" required="required">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Address 2'|trans }}:</label>
										<input type="text" class="form-control" name="address_2" value="{{ profile.address_2 }}">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'City'|trans }}:</label>
										<input type="text" class="form-control" name="city" value="{{ profile.city }}" required="required">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Country'|trans }}:</label>
										{{ mf.selectbox('country', guest.system_countries, profile.country, 1, 'Select country') }}
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'State'|trans }}:</label>
										{# mf.selectbox('state', guest.system_states, profile.state, 0, 'Select state') #}
										<input type="text" class="form-control" name="state" value="{{ profile.state }}">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{{ 'Zip/Postal Code'|trans }}:</label>
										<input type="text" class="form-control" name="postcode" value="{{ profile.postcode }}" required="required">
									</div>
								</div>
						</div>
						<div class="col-md-12 text-center">
							<input class="btn btn-primary" type="submit" value="{{ 'Update profile'|trans }}">
						</div>
					</div>
					</form>
				</div>
				<div class="tab-pane fade" id="tab-password">
					<h4>{{ 'Change password'|trans }}</h4>
					<form method="post" action="" class="api_form" data-api-url="client/client/change_password" data-api-msg="{{ 'Password changed'|trans }}">
						<div class="well">
							<div class="control-group form-group">
								<div class="controls">
									<label>{{ 'Password'|trans }}: </label>
									<input type="password" class="form-control" name="password" value="" required="required">
								</div>
							</div>
							<div class="control-group form-group">
								<div class="controls">
									<label>{{ 'Password confirm'|trans }}: </label>
									<input type="password" class="form-control" name="password_confirm" value="" required="required">
								</div>
							</div>
							<div class="text-center">
								<input class="btn btn-primary" type="submit" value="{{ 'Change password'|trans }}">
							</div>
						</div>
					</form>
				</div>
				<div class="tab-pane fade" id="tab-gravatar">
					<h4>{{ 'Gravatar'|trans }}</h4>
					<div class="well text-center">
						<p><img src="{{ profile.email|gravatar }}" alt="Gravatar" /></p>
						<p>{{ 'Please register with'|trans }} <b>{{ profile.email }}</b> {{ 'at '|trans }} <a target="_blank" href="http://gravatar.com">Gravatar.com</a> {{ 'to change your profile image. Gravatar image updates may not appear immediately.'|trans }}</p>
					</div>
				</div>
				<div class="tab-pane fade" id="tab-currency">
					<h4>{{ 'Currency'|trans }}</h4>
					<div class="well">
						{% if profile.currency %}
							<p>{{ 'Your profile currency is'|trans }} <em>{{ profile.currency }}</em></p>
							<p>{{ 'Create new client profile if you want to manage your money in other currency'|trans }}</p>
						{% else %}
							<p>{{ 'Your profile currency will be defined after your first order. Once your currency is set, all your profile accounting will be managed in that currency and can not be changed.'|trans }}</p>
						{% endif %}
					</div>
				</div>
				<div class="tab-pane fade" id="tab-api">
					<h4>{{ 'API key'|trans }}</h4>
					<div class="well">
						<p>{{ 'API key allows integration with external applications. You will need this key for authentication.'|trans }}</p>
						<p>{{ 'Warning! Resetting the key will break existing applications using it.'|trans }}</p>
						{% if client.client_api_key_get is not empty %}
							<p class="alert alert-info text-center">
								<strong>{{ 'Your API key'|trans }}:</strong><br />{{ client.client_api_key_get }}
							</p>
							<form method="post" action="" class="api_form" data-api-url="client/client/api_key_reset" data-api-msg="{{ 'API key was changed. Please refresh the page.'|trans }}">
								<div class="text-center">
									<input class="btn btn-danger" type="submit" value="{{ 'Reset key'|trans }}">
								</div>
							</form>
						{% else %}
							<p class="alert alert-info text-center">
								<strong>{{ 'No API key yet'|trans }}</strong>
							</p>
							<form method="post" action="" class="api_form" data-api-url="client/client/api_key_reset" data-api-msg="{{ 'API key was changed. Please refresh the page.'|trans }}">
								<div class="text-center">
									<input class="btn btn-success" type="submit" value="{{ 'Create API key'|trans }}">
								</div>
							</form>
						{% endif %}
					</div>
					
				</div>
			</div>
		</div>
	</div>
{% endblock %}
