{% extends request.ajax ? 'layout_blank.phtml' : 'layout_default.phtml' %}

{% block meta_title %}{{ 'Terms and Conditions'|trans }}{% endblock %}

{% block content_before %}
    <h1>{{ company.name }} {{ 'Terms and Conditions'|trans }}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{''|link }}">{{ 'Home'|trans }}</a>
        </li>
        <li class="breadcrumb-item active">{{ company.name }} {{ 'Terms and Conditions'|trans }}</li>
    </ol>
{% endblock %}

{% block content %}
	{{ company.tos|bbmd }}
{% endblock %}
