{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{{ 'Knowledge base'|trans }}{% endblock %}

    {% if request.q %}
        {% set kbcategories = guest.kb_category_get_list({ "q": request.q }) %}
    {% else %}
        {% set kbcategories = guest.kb_category_get_list %}
    {% endif %}

{% block content_before %}
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ 'Knowledge base'|trans }}
                <small>{{ category.description }}</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->
{% endblock %}

{% block content %}
				{% for i, category in kbcategories.list %}
				<h2 id="category-{{ category.id }}">
                    <a href="{{ 'kb'|link }}/{{ category.slug }}">{{ category.title }}</a>
                </h2>
                <hr>
                <div class="list-group">
					{% for i, article in category.articles %}
						<a href="{{ '/kb'|link }}/{{ article.category.slug }}/{{ article.slug }}" class="list-group-item">{{ article.title }}</a>
					{% endfor %}
				</div>

                <hr>
				{% else %}
					<p>
						{{ 'Try using other keyword. No matches not for keyword:'|trans }}
						<b>{{ request.q }}</b>
					</p>
				{% endfor %}
				
			<div class="well">
                <h4>{{ 'What are you looking for?'|trans }}</h4>
				<form method="get" action="{{ 'kb'|link }}">
                    <div class="input-group">
						<input name="q" type="text" class="form-control" value="{{ request.q }}" placeholder="{{ 'What are you looking for?'|trans }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
				</form>
            </div>
{% endblock %}
