<div class="list-group">
	{% if settings.side_menu_home %}
	<a href="{{ ''|link }}" title="{{ 'Home'|trans }}" class="list-group-item{% if request._url == '/' %} active{% endif %}">
		<i class="fa fa-home"></i> {{ 'Home'|trans }}</a>
	{% endif %}
	{% if settings.side_menu_order %}
	<a href="{{ '/order'|link }}" title="{{ 'Order'|trans }}" class="list-group-item{% if request._url starts with '/order/service' %}{% elseif request._url starts with '/order' %} active{% endif %}">
		<i class="fa fa-shopping-cart"></i> {{ 'Order'|trans }}</a>
	{% endif %}
	{% if settings.side_menu_blog and guest.extension_is_on({ "mod": "news"}) %}
	<a href="{{ '/news'|link }}" title="{{ 'Blog'|trans }}" class="list-group-item{% if request._url starts with '/news' %} active{% endif %}">
		<i class="fa fa-bullhorn"></i> {{ 'Blog'|trans }}</a>
	{% endif %}
	{% if settings.side_menu_forum and guest.extension_is_on({ "mod": "forum" }) %}
	<a class="list-group-item{% if request._url starts with '/forum' %} active{% endif %}" href="{{ '/forum'|link }}">
		<i class="fa fa-comments"></i> {{ 'Forum'|trans }}</a>
	{% endif %}
	{% if settings.side_menu_kb and guest.extension_is_on({ "mod": "kb" }) %}
	<a href="{{ 'kb'|link }}" title="{{ 'Knowledge Base'|trans }}" class="list-group-item{% if request._url starts with '/kb' %} active{% endif %}">
		<i class="fa fa-graduation-cap"></i> {{ 'Knowledge Base'|trans }}</a>
	{% endif %}
	{% if settings.side_menu_contact %}
	<a class="list-group-item{% if request._url starts with '/support/contact-us' %} active{% endif %}" href="{{ '/support/contact-us'|link }}">
		<i class="fa fa-envelope"></i> {{ 'Contact us'|trans }}</a>
	{% endif %}
</div>
{% if client %}
	<div class="list-group">
		{% if settings.side_menu_services %}
		<a href="{{ 'order/service'|link }}" title="{{ 'Services'|trans }}" class="list-group-item{% if request._url starts with '/order/service' %} list-group-item-success{% endif %}">
			<span class="text-success"><i class="fa fa-cog"></i> {{ 'Services'|trans }}</span>
		</a>
		{% endif %}
		{% if settings.side_menu_support %}
		<a href="{{ 'support'|link }}" title="{{ 'Tickets'|trans }}" class="list-group-item{% if request._url starts with '/support' %} list-group-item-info{% endif %}">
			<span class="text-info"><i class="fa fa-life-ring"></i> {{ 'Support'|trans }}</span>
		</a>
		{% endif %}
		{% if settings.side_menu_invoices %}
		<a href="{{ 'invoice'|link }}" title="{{ 'Invoices'|trans }}" class="list-group-item{% if request._url starts with '/invoice' %} list-group-item-danger{% endif %}">
			<span class="text-danger"><i class="fa fa-credit-card"></i> {{ 'Invoices'|trans }}</span>
		</a>
		{% endif %}
		<!--<a href="{{ '/client/balance'|link }}" title="{{ 'Payment history'|trans }}" class="list-group-item" ><i class="fa fa-archive"></i> {{ 'Payment history'|trans }}</a>-->
	</div>
{% else %}
	<div class="list-group">
		{% if settings.side_menu_register %}
		<a href="{{ '/login'|link }}" title="{{ 'Sign in / Register'|trans }}" class="list-group-item list-group-item-success" >{{ 'Sign in / Register'|trans }}</a>
		{% endif %}
	</div>
{% endif %}
