{# <ol class="breadcrumb">
    {% if selected == 1 %}
		<li class="active">1 {{ 'Select product'|trans }}</li>
	{% else %}
		<li>
			<a href="{{ 'order'|link }}">1 {{ 'Select product'|trans }}</a>
		</li>
	{% endif %}
	{% if selected == 2 %}
		<li class="active">2 {{ 'Configure'|trans }} {% if product %} {{ product.title }}{% endif %}</li>
	{% else %}
		<li>2 {{ 'Configure'|trans }}</li>
	{% endif %}
	<li class="{% if selected == 3 %}active{% endif %}">3 {{ 'Confirm'|trans }}</li>
	<li class="{% if selected == 4 %}active{% endif %}">4 {{ 'Checkout'|trans }}</li>
</ol> #}
