{% if product.addons|length > 0 %}
<div class="addons well" style="display: none;">
	<h4>{% trans 'Addons & extras' %}</h4>
	<ul class="list-group">
		{% for addon in product.addons %}
			<li class="list-group-item">
				<h4 class="list-group-item-heading">
					<input type="hidden" name="addons[{{ addon.id }}][selected]" value="0">
					<input type="checkbox" name="addons[{{ addon.id }}][selected]" value="1" id="addon_{{ addon.id }}">
					{{ addon.title }}
				</h4>
				<p class="list-group-item-text form-inline">
					{{ addon.description|bbmd }}
					{% if addon.pricing.type is same as('recurrent') %}
					<div class="form-group">
						<div class="input-group">
							<select name="addons[{{ addon.id }}][period]" class="addon-period-selector form-control" rel="addon-periods-{{ addon.id }}">
							{% for code,prices in addon.pricing.recurrent %}
								{% if prices.enabled %}
								<option value="{{code}}">{{ periods[code] }}</option>
								{% endif %}
							{% endfor %}
							</select>
							<div id="addon-periods-{{ addon.id }}" class="input-group-addon">
							{% for code,prices in addon.pricing.recurrent %}
								<span class="{{code}}">{{ (prices.price + prices.setup) | money_convert }}</span>
							{% endfor %}
							</div>
						</div>
					</div>
					{% endif %}

					{% if addon.pricing.type is same as('once') %}
						<h4 class="text-right"><strong>{{ (addon.pricing.once.price + addon.pricing.once.setup) | money_convert }}</strong></h4>
					{% endif %}

					{% if addon.pricing.type is same as('free') %}
						<h4 class="text-right"><strong>{{ 0 | money_convert }}</strong></h4>
					{% endif %}	
				</p>	
			</li>
		{% endfor %}
		<li class="list-group-item"></li>
	</ul>
	<div class="text-center" >
		<button class="btn btn-success btn-lg" type="submit">{% trans 'Order now' %}</button>
	</div>
</div>
{% endif %}