{% block subject %}[{{ guest.system_company.name }}] {{ ticket.subject }}{% endblock %}
{% block content %}
{% apply markdown %}
Hi {{ staff.name }},

 **{{ ticket.client.first_name }} {{ ticket.client.last_name }}** opened a new support ticket #{{ ticket.id }}

***

{{ ticket.messages[0].content }}

***

Ticket ID: #{{ticket.id}}   
Department: {{ticket.helpdesk.name}}   
Status: {{ticket.status|title}}

Reply at {{'support/ticket'|alink }}/{{ ticket.id }}

{{ guest.system_company.signature }}

{% endapply %}
{% endblock %}
