{% block subject %}[{{ guest.system_company.name }}] {{ order.title }} Activated{% endblock %}
{% block content %}
{% apply markdown %}

Hello {{ c.first_name }} {{ c.last_name }},

Thank you for ordering with us! Your hosting account has now been set up. This email contains all the information you will need in order to begin using your service.

If you have requested a domain name during the signup, please keep in mind that 
your domain name will not be visible  on the internet instantly. 
This process is called propagation and can take up to 48 hours. 
Your website and email will not function until your domain has propagated.

**{{ order.title }}**

Activated: {{ order.activated_at|bb_date }}
{% if order.expires_at %}Expires: {{ order.expires_at|bb_date }} {% endif %}
{% if order.period %}
Billing period:

{{ order.total | money(order.currency) }}
{{ order.period | period_title }}

{% endif %}       

**New Account Information**


Hosting Package: {{ service.hosting_plan.name }}    
Domain: {{ service.domain }}    
IP Address: {{ service.server.ip }}


**Control Panel Login Details**

Username: {{ service.username }}    
Password: {{ password }}     
Control Panel URL: {{ service.server.cpanel_url }}


**Server Information**

Server Name: {{ service.server.name }}     
Server IP: {{ service.server.ip }}

If you are using an existing domain with your new hosting account, you  will 
need to update the domain settings to point it to the nameservers listed below.

Nameserver 1: {{ service.server.ns1 }}   
Nameserver 2: {{ service.server.ns2 }}   
{% if  service.server.ns3 %}Nameserver 3: {{ service.server.ns3 }}   {% endif %}
{% if  service.server.ns4 %}Nameserver 4: {{ service.server.ns4 }}   {% endif %}

**Uploading Your Website**


You may use one of the addresses given below to manage your web site:


Temporary FTP Hostname: {{ service.server.ip }}    
Full FTP Hostname: {{ service.domain }}    
FTP Username: {{ service.username }}    
FTP Password: {{ password }}    

You must upload files to the **public_html** folder!
Thank you for choosing us.


Login to members area: {{'login'|link({'email' : c.email }) }}
Manage order: {{ 'order/service/manage'|link }}/{{ order.id }}

{{ guest.system_company.signature }}

{% endapply %}
{% endblock %}
