{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Paid support settings' %}{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}
<ul>
    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li><a href="{{ 'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="lastB">{% trans 'Paid support settings' %}</li>
</ul>
{% endblock %}

{% block content %}

<div class="widget">
    <div class="head">
        <h5 class="iCog">{% trans 'Paid support settings' %}</h5>
    </div>

    {% set params = admin.extension_config_get({"ext":"mod_paidsupport"}) %}
    <form method="post" action="{{ 'api/admin/extension/config_save'|link }}" class="mainForm api-form" data-api-msg="Settings updated">
        <fieldset>
        <div class="rowElem">
            <label>{% trans 'Ticket price:' %}</label>
            <div class="formRight">
                <input type="text" name="ticket_price" value="{{ params.ticket_price }}" />
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem">
            <label>{% trans 'Error message:' %}</label>
            <div class="formRight">
                <input type="text" name="error_msg" value="{{ params.error_msg }}" />
            </div>
            <div class="fix"></div>
        </div>


            <input type="hidden" name="ext" value="mod_paidsupport" />
        <input type="submit" value="{% trans 'Update settings' %}" class="greyishBtn submitForm" />
        </fieldset>
    </form>
</div>

{% endblock %}