<div class="steps">

<div class="grid_4 alpha{% if selected == 1 %} selected{% endif %}">
    <span>1</span>
    <p>{% trans 'Select product' %}</p>
</div>

<div class="grid_4{% if selected == 2 %} selected{% endif %}">
    <span>2</span>
    <p>{% trans 'Configure' %}</p>
</div>

<div class="grid_4{% if selected == 3 %} selected{% endif %}">
    <span>3</span>
    <p>{% trans 'Confirm' %}</p>
</div>

<div class="grid_4 omega{% if selected == 4 %} selected{% endif %}">
    <span>4</span>
    <p>{% trans 'Checkout' %}</p>
</div>

<div class="clear"></div>
</div>