name: 'Spellcheck'
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          incremental_files_only: true #TODO: Change this once I have fixed all of the issues :)
          config: 'cspell.json'
