name: Laravel-linter

on:
  push:
    branches:
      - 'lara'
  pull_request:
    branches:
      - 'lara'
  pull_request_target:
    branches:
      - 'lara'

jobs:
  linter:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.1
            name: Unit
            skip-web-check: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Composer validate
        run: |
          composer validate
      - name: Composer install
        run: |
          composer install --prefer-dist --no-interaction --no-progress
      - name: Execute Pint
        run: |
          ./vendor/bin/pint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
