name: Laravel-linter

on:
  push:
    branches:
      - 'lara'
  pull_request_target:

jobs:
  linter:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.1
            name: Unit
            skip-web-check: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Composer validate
        run: |
          composer validate
      - name: Composer install
        run: |
          composer install --prefer-dist --no-interaction --no-progress
      - name: Execute Pint
        run: |
          ./vendor/bin/pint --test
