name: Merge Hold

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  merge-hold:
    name: 'Check for Merge Hold'
    
    runs-on: ubuntu-latest
    steps:
      - name: 'Prevent Merging (Merge Hold)'
        if: ${{ contains(github.event.pull_request.labels.*.name, 'merge-hold') }}
        run: |
          echo "Pull request labeled 'merge-hold'"
          echo "The pull request cannot be merged until the 'merge-hold' label is removed."
          exit 1
      
      - name: 'Allow Merging (No Merge Hold)'
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'merge-hold') }}
        run: |
          echo "Pull request not labeled 'merge-hold'"
          echo "The pull request can be merged as no 'merge-hold' label is set."
          exit 0
