<?php

declare(strict_types=1);
/**
 * Copyright 2022-2025 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Tests\Modules\Client\Entity;

use Box\Mod\Client\Entity\Client;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for Client entity.
 *
 * Tests entity creation, getters, setters, lifecycle callbacks,
 * and API array conversion.
 */
class ClientTest extends TestCase
{
    /**
     * Test that entity can be created with required fields.
     */
    public function testEntityCreation(): void
    {
        $client = new Client();
        $client->setEmail('test@example.com');
        $client->setPass('hashedpassword');
        $client->setFirstName('John');
        $client->setLastName('Doe');

        $this->assertEquals('test@example.com', $client->getEmail());
        $this->assertEquals('hashedpassword', $client->getPass());
        $this->assertEquals('John', $client->getFirstName());
        $this->assertEquals('Doe', $client->getLastName());
    }

    /**
     * Test status constants are defined.
     */
    public function testStatusConstants(): void
    {
        $this->assertEquals('active', Client::STATUS_ACTIVE);
        $this->assertEquals('suspended', Client::STATUS_SUSPENDED);
        $this->assertEquals('canceled', Client::STATUS_CANCELED);
    }

    /**
     * Test default status is active.
     */
    public function testDefaultStatus(): void
    {
        $client = new Client();
        $this->assertEquals(Client::STATUS_ACTIVE, $client->getStatus());
    }

    /**
     * Test getFullName() combines first and last name.
     */
    public function testGetFullName(): void
    {
        $client = new Client();
        $client->setFirstName('John');
        $client->setLastName('Doe');

        $this->assertEquals('John Doe', $client->getFullName());
    }

    /**
     * Test getFullName() handles null values.
     */
    public function testGetFullNameWithNullValues(): void
    {
        $client = new Client();

        // Both null
        $this->assertEquals('', $client->getFullName());

        // Only first name
        $client->setFirstName('John');
        $this->assertEquals('John', $client->getFullName());

        // Only last name
        $client = new Client();
        $client->setLastName('Doe');
        $this->assertEquals('Doe', $client->getFullName());
    }

    /**
     * Test lifecycle callbacks set timestamps.
     */
    public function testLifecycleCallbacksSetTimestamps(): void
    {
        $client = new Client();

        // Manually trigger prePersist
        $client->onPrePersist();

        $this->assertInstanceOf(\DateTime::class, $client->getCreatedAt());
        $this->assertInstanceOf(\DateTime::class, $client->getUpdatedAt());

        $createdAt = $client->getCreatedAt();

        // Sleep briefly to ensure timestamp difference
        sleep(1);

        // Manually trigger preUpdate
        $client->onPreUpdate();

        $this->assertEquals($createdAt, $client->getCreatedAt(), 'created_at should not change on update');
        $this->assertGreaterThan($createdAt, $client->getUpdatedAt(), 'updated_at should be newer');
    }

    /**
     * Test toApiArray() returns expected structure.
     *
     * Note: This test uses reflection to set ID since it's auto-generated by Doctrine.
     */
    public function testToApiArrayReturnsExpectedStructure(): void
    {
        $client = new Client();
        $client->setEmail('test@example.com');
        $client->setPass('hashedpass');
        $client->setFirstName('John');
        $client->setLastName('Doe');
        $client->setStatus(Client::STATUS_ACTIVE);
        $client->onPrePersist(); // Set timestamps

        // Set ID via reflection (normally done by Doctrine)
        $reflection = new \ReflectionClass($client);
        $idProperty = $reflection->getProperty('id');
        $idProperty->setAccessible(true);
        $idProperty->setValue($client, 1);

        $array = $client->toApiArray();

        // Assert required keys exist
        $this->assertArrayHasKey('id', $array);
        $this->assertArrayHasKey('email', $array);
        $this->assertArrayHasKey('first_name', $array);
        $this->assertArrayHasKey('last_name', $array);
        $this->assertArrayHasKey('created_at', $array);

        // Assert values match
        $this->assertEquals(1, $array['id']);
        $this->assertEquals('test@example.com', $array['email']);
        $this->assertEquals('John', $array['first_name']);
        $this->assertEquals('Doe', $array['last_name']);
    }

    /**
     * Test toApiArray() includes custom fields when set.
     */
    public function testToApiArrayIncludesCustomFields(): void
    {
        $client = new Client();
        $client->setEmail('test@example.com');
        $client->setPass('hashedpass');
        $client->setCustom1('Custom Value 1');
        $client->setCustom2('Custom Value 2');
        $client->onPrePersist();

        // Set ID via reflection
        $reflection = new \ReflectionClass($client);
        $idProperty = $reflection->getProperty('id');
        $idProperty->setAccessible(true);
        $idProperty->setValue($client, 1);

        $array = $client->toApiArray();

        $this->assertArrayHasKey('custom_1', $array);
        $this->assertArrayHasKey('custom_2', $array);
        $this->assertEquals('Custom Value 1', $array['custom_1']);
        $this->assertEquals('Custom Value 2', $array['custom_2']);
    }

    /**
     * Test toApiArray() excludes empty custom fields.
     */
    public function testToApiArrayExcludesEmptyCustomFields(): void
    {
        $client = new Client();
        $client->setEmail('test@example.com');
        $client->setPass('hashedpass');
        $client->onPrePersist();

        // Set ID via reflection
        $reflection = new \ReflectionClass($client);
        $idProperty = $reflection->getProperty('id');
        $idProperty->setAccessible(true);
        $idProperty->setValue($client, 1);

        $array = $client->toApiArray();

        // Empty custom fields should not be in array
        $this->assertArrayNotHasKey('custom_1', $array);
        $this->assertArrayNotHasKey('custom_2', $array);
    }

    /**
     * Test all getters and setters work correctly.
     */
    public function testGettersAndSetters(): void
    {
        $client = new Client();

        $client->setAid(123);
        $this->assertEquals(123, $client->getAid());

        $client->setClientGroupId(5);
        $this->assertEquals(5, $client->getClientGroupId());

        $client->setCompany('ACME Corp');
        $this->assertEquals('ACME Corp', $client->getCompany());

        $client->setCompanyVat('VAT123');
        $this->assertEquals('VAT123', $client->getCompanyVat());

        $client->setPhoneCc('1');
        $this->assertEquals('1', $client->getPhoneCc());

        $client->setPhone('555-1234');
        $this->assertEquals('555-1234', $client->getPhone());

        $client->setCountry('US');
        $this->assertEquals('US', $client->getCountry());

        $client->setCurrency('USD');
        $this->assertEquals('USD', $client->getCurrency());
    }

    /**
     * Test nullable fields work correctly.
     */
    public function testNullableFields(): void
    {
        $client = new Client();

        // These should all be nullable
        $this->assertNull($client->getAid());
        $this->assertNull($client->getCompany());
        $this->assertNull($client->getPhoneCc());
        $this->assertNull($client->getBirthday());
        $this->assertNull($client->getCustom1());
    }
}
