<?php

declare(strict_types=1);
/**
 * Copyright 2022-2026 FOSSBilling
 * SPDX-License-Identifier: Apache-2.0.
 *
 * @copyright FOSSBilling (https://www.fossbilling.org)
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache-2.0
 */

namespace Box\Mod\Servicedomain\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Doctrine\TimestampTrait;
use FOSSBilling\Doctrine\TimestampInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Servicedomain\Repository\TldRepository::class)]
#[ORM\Table(name: 'tld')]
#[ORM\Index(name: 'tld_registrar_id_idx', columns: ['tld_registrar_id'])]
#[ORM\HasLifecycleCallbacks]
class Tld implements TimestampInterface
{
    use TimestampTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: TldRegistrar::class)]
    #[ORM\JoinColumn(name: 'tld_registrar_id', referencedColumnName: 'id', nullable: true)]
    private ?TldRegistrar $registrar = null;

    #[ORM\Column(type: Types::STRING, length: 64, nullable: true, unique: true)]
    private ?string $tld = null;

    #[ORM\Column(name: 'price_registration', type: Types::DECIMAL, precision: 18, scale: 2, nullable: true, options: ['default' => '0.00'])]
    private ?string $priceRegistration = null;

    #[ORM\Column(name: 'price_renew', type: Types::DECIMAL, precision: 18, scale: 2, nullable: true, options: ['default' => '0.00'])]
    private ?string $priceRenew = null;

    #[ORM\Column(name: 'price_transfer', type: Types::DECIMAL, precision: 18, scale: 2, nullable: true, options: ['default' => '0.00'])]
    private ?string $priceTransfer = null;

    #[ORM\Column(name: 'allow_register', type: Types::BOOLEAN, nullable: true)]
    private ?bool $allowRegister = null;

    #[ORM\Column(name: 'allow_transfer', type: Types::BOOLEAN, nullable: true)]
    private ?bool $allowTransfer = null;

    #[ORM\Column(name: 'require_transfer_code', type: Types::BOOLEAN, nullable: true)]
    private ?bool $requireTransferCode = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true, options: ['default' => true])]
    private ?bool $active = true;

    #[ORM\Column(name: 'min_years', type: Types::SMALLINT, nullable: true)]
    private ?int $minYears = null;

    /**
     * Comma-separated list of the exact registration periods (in years) this TLD may be
     * ordered for, e.g. "1,2,3,5,10". Null means any period from min_years upwards is
     * allowed, matching the legacy behavior.
     */
    #[ORM\Column(name: 'periods', type: Types::STRING, length: 255, nullable: true)]
    private ?string $periods = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegistrar(): ?TldRegistrar
    {
        return $this->registrar;
    }

    public function setRegistrar(?TldRegistrar $registrar): self
    {
        $this->registrar = $registrar;

        return $this;
    }

    public function getTld(): ?string
    {
        return $this->tld;
    }

    public function setTld(?string $tld): self
    {
        $this->tld = $tld;

        return $this;
    }

    public function getPriceRegistration(): ?string
    {
        return $this->priceRegistration;
    }

    public function setPriceRegistration(?string $priceRegistration): self
    {
        $this->priceRegistration = $priceRegistration;

        return $this;
    }

    public function getPriceRenew(): ?string
    {
        return $this->priceRenew;
    }

    public function setPriceRenew(?string $priceRenew): self
    {
        $this->priceRenew = $priceRenew;

        return $this;
    }

    public function getPriceTransfer(): ?string
    {
        return $this->priceTransfer;
    }

    public function setPriceTransfer(?string $priceTransfer): self
    {
        $this->priceTransfer = $priceTransfer;

        return $this;
    }

    public function isAllowRegister(): ?bool
    {
        return $this->allowRegister;
    }

    public function setAllowRegister(?bool $allowRegister): self
    {
        $this->allowRegister = $allowRegister;

        return $this;
    }

    public function isAllowTransfer(): ?bool
    {
        return $this->allowTransfer;
    }

    public function setAllowTransfer(?bool $allowTransfer): self
    {
        $this->allowTransfer = $allowTransfer;

        return $this;
    }

    public function isRequireTransferCode(): ?bool
    {
        return $this->requireTransferCode;
    }

    public function setRequireTransferCode(?bool $requireTransferCode): self
    {
        $this->requireTransferCode = $requireTransferCode;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getMinYears(): ?int
    {
        return $this->minYears;
    }

    public function setMinYears(?int $minYears): self
    {
        $this->minYears = $minYears;

        return $this;
    }

    public function getPeriods(): ?string
    {
        return $this->periods;
    }

    public function setPeriods(?string $periods): self
    {
        $this->periods = $periods;

        return $this;
    }

    /**
     * The allowed registration periods (in years), sorted ascending, or null when
     * this TLD has no explicit period list and any period from min_years upwards
     * is allowed.
     *
     * @return int[]|null
     */
    public function getPeriodsArray(): ?array
    {
        if ($this->periods === null || trim($this->periods) === '') {
            return null;
        }

        $years = array_unique(array_map(intval(...), explode(',', $this->periods)));
        sort($years);

        return $years;
    }
}
